//! Control rows: what a harness writes into the user role that is neither a
//! human prompt nor model output.
//!
//! Claude Code stores a slash command as three user records chained by
//! `parentUuid` — a caveat, the `<command-name>` / `<command-message>` /
//! `<command-args>` invocation, and the `<local-command-stdout>` output — and
//! it also writes task notifications, hook output, bash pass-through and
//! `<system-reminder>` blocks into the same role. Codex prepends
//! `<environment_context>` and its siblings to a turn. None of them is a
//! prompt, and every consumer that groups a session into human turns has to
//! recognise all of them, so they are classified once, here, and stored on
//! the row as `session_events.control_kind`: the discovery scan that derives
//! `first_prompt`, the record walk that writes `history`, and prompt
//! attribution all ask this module the same question rather than keeping
//! prefix lists of their own.
//!
//! The vocabulary is [`ControlKind`]. A slash-command triad is additionally
//! grouped into one `session_markers` row of `kind = "slash_command"` whose
//! payload names the command and the three rows, so a consumer can read the
//! command without re-reading the transcript.

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use std::collections::HashMap;

/// Why a row in the user role is not a human prompt.
///
/// Stored as its `as_str` spelling in `session_events.control_kind`, which is
/// null for a genuine prompt and for every model-output row.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum ControlKind {
    /// Claude: the "Caveat: The messages below were generated by the user
    /// while running local commands" record that opens a slash-command triad.
    SlashCommandCaveat,
    /// Claude: the `<command-name>` / `<command-message>` / `<command-args>`
    /// record.
    SlashCommandInvocation,
    /// Claude: the `<local-command-stdout>` / `<local-command-stderr>` record.
    SlashCommandOutput,
    /// Claude: a `<task-notification>` about a background task, recognised by
    /// `origin.kind`, `attachment.commandMode` or the wrapper itself.
    TaskNotification,
    /// Claude: the output of a hook, `<user-prompt-submit-hook>` and the rest.
    HookOutput,
    /// Claude: `<bash-input>`, a shell command the human ran in pass-through
    /// mode.
    BashPassthroughInput,
    /// Claude: `<bash-stdout>` / `<bash-stderr>`, that command's output.
    BashPassthroughOutput,
    /// Claude: a `<system-reminder>` block injected into user content.
    SystemReminder,
    /// Codex: `<environment_context>`, `<permissions instructions>`,
    /// `# AGENTS.md` and the other context the app prepends to a turn.
    CodexContextWrapper,
    /// Claude: a record flagged `isMeta: true` that no more specific kind
    /// above describes.
    Meta,
    /// Claude: a bare `/resume <id>` or `/continue <id>` the human typed.
    ResumeMarker,
}

impl ControlKind {
    /// Every kind, in declaration order: the closed vocabulary a stored or
    /// contributed `control_kind` must come from.
    pub(crate) const ALL: &'static [ControlKind] = &[
        ControlKind::SlashCommandCaveat,
        ControlKind::SlashCommandInvocation,
        ControlKind::SlashCommandOutput,
        ControlKind::TaskNotification,
        ControlKind::HookOutput,
        ControlKind::BashPassthroughInput,
        ControlKind::BashPassthroughOutput,
        ControlKind::SystemReminder,
        ControlKind::CodexContextWrapper,
        ControlKind::Meta,
        ControlKind::ResumeMarker,
    ];

    /// The inverse of [`Self::as_str`]: `None` for any spelling not in the
    /// vocabulary, which is what source-evidence validation refuses.
    pub(crate) fn parse(value: &str) -> Option<Self> {
        Self::ALL
            .iter()
            .copied()
            .find(|kind| kind.as_str() == value)
    }

    /// The `session_events.control_kind` spelling.
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            ControlKind::SlashCommandCaveat => "slash_command_caveat",
            ControlKind::SlashCommandInvocation => "slash_command_invocation",
            ControlKind::SlashCommandOutput => "slash_command_output",
            ControlKind::TaskNotification => "task_notification",
            ControlKind::HookOutput => "hook_output",
            ControlKind::BashPassthroughInput => "bash_passthrough_input",
            ControlKind::BashPassthroughOutput => "bash_passthrough_output",
            ControlKind::SystemReminder => "system_reminder",
            ControlKind::CodexContextWrapper => "codex_context_wrapper",
            ControlKind::Meta => "meta",
            ControlKind::ResumeMarker => "resume_marker",
        }
    }
}

/// `session_markers.kind` for one grouped slash-command triad.
pub(crate) const SLASH_COMMAND_MARKER_KIND: &str = "slash_command";

/// The caveat Claude Code writes ahead of a local command's records.
pub(crate) const CLAUDE_CAVEAT_PREFIX: &str =
    "Caveat: The messages below were generated by the user while running local commands";

const SLASH_COMMAND_TAGS: &[&str] = &["<command-name>", "<command-message>", "<command-args>"];
const LOCAL_COMMAND_OUTPUT_TAGS: &[&str] = &["<local-command-stdout>", "<local-command-stderr>"];
const TASK_NOTIFICATION_TAG: &str = "<task-notification>";
const TASK_NOTIFICATION_MODE: &str = "task-notification";
const SYSTEM_REMINDER_OPEN: &str = "<system-reminder>";
const SYSTEM_REMINDER_CLOSE: &str = "</system-reminder>";

/// Classify Claude user text by the wrapper it opens with.
///
/// Prefix rules, deliberately: a prompt that *mentions* `<command-name>` in
/// its second paragraph is a prompt. The wrappers Claude Code writes always
/// open the record.
pub(crate) fn claude_text_control_kind(text: &str) -> Option<ControlKind> {
    let text = text.trim_start();
    if text.starts_with(CLAUDE_CAVEAT_PREFIX) {
        return Some(ControlKind::SlashCommandCaveat);
    }
    if SLASH_COMMAND_TAGS.iter().any(|tag| text.starts_with(tag)) {
        return Some(ControlKind::SlashCommandInvocation);
    }
    if LOCAL_COMMAND_OUTPUT_TAGS
        .iter()
        .any(|tag| text.starts_with(tag))
    {
        return Some(ControlKind::SlashCommandOutput);
    }
    if text.starts_with(TASK_NOTIFICATION_TAG) {
        return Some(ControlKind::TaskNotification);
    }
    if text.starts_with("<bash-input>") {
        return Some(ControlKind::BashPassthroughInput);
    }
    if text.starts_with("<bash-stdout>") || text.starts_with("<bash-stderr>") {
        return Some(ControlKind::BashPassthroughOutput);
    }
    if opens_with_hook_tag(text) {
        return Some(ControlKind::HookOutput);
    }
    if bare_resume_marker(text) {
        return Some(ControlKind::ResumeMarker);
    }
    None
}

/// `<user-prompt-submit-hook>`, `<session-start-hook>`, and whichever hook
/// wrapper Claude Code adds next: an opening tag whose name ends in `-hook`.
fn opens_with_hook_tag(text: &str) -> bool {
    let Some(rest) = text.strip_prefix('<') else {
        return false;
    };
    let name_end = rest
        .find(|c: char| c == '>' || c.is_whitespace())
        .unwrap_or(rest.len());
    rest[..name_end].ends_with("-hook")
}

/// `/resume` or `/continue` as typed, with or without a target.
///
/// The same rule `continuity` reads the resume target by: the first token
/// after the slash, case-insensitively.
fn bare_resume_marker(text: &str) -> bool {
    let Some(after_slash) = text.strip_prefix('/') else {
        return false;
    };
    let command_end = after_slash
        .find(char::is_whitespace)
        .unwrap_or(after_slash.len());
    let command = after_slash[..command_end].to_ascii_lowercase();
    command == "resume" || command == "continue"
}

/// Classify one Claude user record.
///
/// `text` is the record's own user text with any `<system-reminder>` blocks
/// already removed, so a reminder Claude Code prepends to a wrapper does not
/// hide the wrapper. The envelope fields are consulted first: a task
/// notification says what it is in `origin.kind` or
/// `attachment.commandMode` whatever its text looks like. `isMeta` comes
/// last, so a meta-flagged slash command keeps its specific kind and only a
/// meta row nothing else describes becomes [`ControlKind::Meta`]. A meta
/// record whose text is nothing but reminders is not `Meta` either: it has no
/// text of its own to be meta about, and its reminders are stored as
/// `system_reminder` rows exactly as a prompt's would be.
pub(crate) fn claude_record_control_kind(
    obj: &Map<String, Value>,
    text: &str,
) -> Option<ControlKind> {
    if origin_kind(obj) == Some(TASK_NOTIFICATION_MODE)
        || command_mode(obj) == Some(TASK_NOTIFICATION_MODE)
    {
        return Some(ControlKind::TaskNotification);
    }
    if let Some(kind) = claude_text_control_kind(text) {
        return Some(kind);
    }
    if !text.trim().is_empty() && obj.get("isMeta").and_then(Value::as_bool) == Some(true) {
        return Some(ControlKind::Meta);
    }
    None
}

/// `origin.kind`, verbatim.
pub(crate) fn origin_kind(obj: &Map<String, Value>) -> Option<&str> {
    obj.get("origin")
        .and_then(|origin| origin.get("kind"))
        .and_then(Value::as_str)
        .filter(|kind| !kind.is_empty())
}

/// `attachment.commandMode`, verbatim.
pub(crate) fn command_mode(obj: &Map<String, Value>) -> Option<&str> {
    obj.get("attachment")
        .and_then(|attachment| attachment.get("commandMode"))
        .and_then(Value::as_str)
        .filter(|mode| !mode.is_empty())
}

/// `attachment.type`, verbatim.
pub(crate) fn attachment_type(obj: &Map<String, Value>) -> Option<&str> {
    obj.get("attachment")
        .and_then(|attachment| attachment.get("type"))
        .and_then(Value::as_str)
        .filter(|kind| !kind.is_empty())
}

/// Whether Codex user text is app-injected context rather than a prompt.
///
/// Delegates to the one implementation shallow discovery and the rollout walk
/// already share, so the two cannot disagree about which rows are prompts.
pub(crate) fn codex_text_control_kind(text: &str) -> Option<ControlKind> {
    super::codex::is_control_context(text).then_some(ControlKind::CodexContextWrapper)
}

/// The body of the first `<tag>…</tag>` element in `text`.
pub(crate) fn tag_body<'a>(text: &'a str, tag: &str) -> Option<&'a str> {
    let open = format!("<{tag}>");
    let close = format!("</{tag}>");
    let start = text.find(&open)? + open.len();
    let end = text[start..].find(&close)? + start;
    Some(&text[start..end])
}

/// The three elements of a slash-command invocation record.
///
/// `<command-args>` is absent when the command took none, and the elements
/// can arrive in either order, so each is read independently rather than by
/// position. Values are the element bodies as written, whitespace included.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct SlashCommandFields {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command_args: Option<String>,
}

pub(crate) fn parse_slash_command(text: &str) -> SlashCommandFields {
    SlashCommandFields {
        command_name: tag_body(text, "command-name").map(str::to_string),
        command_message: tag_body(text, "command-message").map(str::to_string),
        command_args: tag_body(text, "command-args").map(str::to_string),
    }
}

/// UTF-8 bytes of a local command's output, wrapper excluded.
///
/// Measured over what the command printed rather than over the record, so a
/// consumer summing output volume does not count the tags Claude Code added.
/// Text that carries no wrapper is measured whole.
pub(crate) fn local_command_output_bytes(text: &str) -> usize {
    let text = text.trim();
    for tag in ["local-command-stdout", "local-command-stderr"] {
        if let Some(body) = tag_body(text, tag) {
            return body.len();
        }
    }
    text.len()
}

/// User text with its `<system-reminder>` blocks separated out.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) struct ReminderSplit {
    /// What remains once every reminder is removed, trimmed. Empty when the
    /// text was nothing but reminders.
    pub prompt: String,
    /// Each reminder block verbatim, tags included, in text order. Kept whole
    /// because the bytes are the fact an overhead analysis wants.
    pub reminders: Vec<String>,
}

/// Separate the `<system-reminder>…</system-reminder>` blocks Claude Code
/// injects into user content from the text the human typed.
///
/// A reminder that never closes runs to the end of the text: the wrapper
/// opened, so what follows is the harness's, not the human's.
pub(crate) fn split_system_reminders(text: &str) -> ReminderSplit {
    let mut split = ReminderSplit::default();
    let mut prompt = String::new();
    let mut rest = text;
    while let Some(start) = rest.find(SYSTEM_REMINDER_OPEN) {
        prompt.push_str(&rest[..start]);
        let after_open = &rest[start..];
        match after_open.find(SYSTEM_REMINDER_CLOSE) {
            Some(close) => {
                let end = close + SYSTEM_REMINDER_CLOSE.len();
                split.reminders.push(after_open[..end].to_string());
                rest = &after_open[end..];
            }
            None => {
                split.reminders.push(after_open.to_string());
                rest = "";
            }
        }
    }
    prompt.push_str(rest);
    split.prompt = prompt.trim().to_string();
    split
}

/// One control row as the Claude record walk saw it, for the triad walk.
pub(crate) struct ControlRow<'a> {
    pub session_id: &'a str,
    pub uuid: &'a str,
    pub parent_uuid: Option<&'a str>,
    /// The `session_events.event_uid` of the row's text event.
    pub event_uid: &'a str,
    pub ts_ms: i64,
    pub kind: ControlKind,
    pub text: &'a str,
    pub origin_kind: Option<&'a str>,
    pub command_mode: Option<&'a str>,
    pub attachment_type: Option<&'a str>,
}

/// The invocation the walk is still completing, per session.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct PendingSlashCommand {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    caveat_uuid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    caveat_event_uid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    invocation: Option<PendingInvocation>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct PendingInvocation {
    uuid: String,
    event_uid: String,
    ts_ms: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    parent_uuid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    caveat_event_uid: Option<String>,
    #[serde(default)]
    fields: SlashCommandFields,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    command_mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    origin_kind: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    attachment_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    output_event_uid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    stdout_bytes: Option<usize>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    stderr_event_uid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    stderr_bytes: Option<usize>,
    /// The last record chained onto this invocation, which the next output
    /// row may hang off instead of the invocation itself.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    last_uuid: Option<String>,
}

/// The `slash_command` marker a triad walk produces or updates.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct SlashCommandMarker {
    pub marker_uid: String,
    /// The invocation record's uuid.
    pub message_id: String,
    /// The caveat when the invocation is chained to one, else the
    /// invocation's own parent.
    pub parent_id: Option<String>,
    pub ts_ms: i64,
    pub payload: Vec<(&'static str, Value)>,
}

/// The triad walk, resumable.
///
/// A slash command's three records are chained by `parentUuid`, and the
/// record walk sees one record at a time, so the caveat and invocation are
/// remembered until the output row that names them arrives. Keyed by session
/// because a sidecar's records are attributed to the child while its file
/// order interleaves nothing else. Carried in the transcript cursor so a triad
/// split across two hydration passes is still grouped.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct SlashCommandTriads {
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pending: HashMap<String, PendingSlashCommand>,
}

impl SlashCommandTriads {
    pub(crate) fn is_empty(&self) -> bool {
        self.pending.is_empty()
    }

    /// Fold one classified control row in.
    ///
    /// Returns the marker to write when the row completes or extends a
    /// triad: on the invocation, and again on each chained output row. A row
    /// of another kind, or an output row that is not chained to the pending
    /// invocation, changes nothing — it is still stored with its own
    /// `control_kind`, just not grouped.
    pub(crate) fn observe(&mut self, row: &ControlRow<'_>) -> Option<SlashCommandMarker> {
        match row.kind {
            ControlKind::SlashCommandCaveat => {
                self.pending.insert(
                    row.session_id.to_string(),
                    PendingSlashCommand {
                        caveat_uuid: Some(row.uuid.to_string()),
                        caveat_event_uid: Some(row.event_uid.to_string()),
                        invocation: None,
                    },
                );
                None
            }
            ControlKind::SlashCommandInvocation => {
                let entry = self.pending.entry(row.session_id.to_string()).or_default();
                let chained_to_caveat =
                    row.parent_uuid.is_some() && entry.caveat_uuid.as_deref() == row.parent_uuid;
                let caveat_event_uid = if chained_to_caveat {
                    entry.caveat_event_uid.clone()
                } else {
                    None
                };
                let invocation = PendingInvocation {
                    uuid: row.uuid.to_string(),
                    event_uid: row.event_uid.to_string(),
                    ts_ms: row.ts_ms,
                    parent_uuid: row.parent_uuid.map(str::to_string),
                    caveat_event_uid,
                    fields: parse_slash_command(row.text),
                    command_mode: row.command_mode.map(str::to_string),
                    origin_kind: row.origin_kind.map(str::to_string),
                    attachment_type: row.attachment_type.map(str::to_string),
                    output_event_uid: None,
                    stdout_bytes: None,
                    stderr_event_uid: None,
                    stderr_bytes: None,
                    last_uuid: None,
                };
                let marker = invocation.marker();
                entry.invocation = Some(invocation);
                Some(marker)
            }
            ControlKind::SlashCommandOutput => {
                let entry = self.pending.get_mut(row.session_id)?;
                let invocation = entry.invocation.as_mut()?;
                let chained = row.parent_uuid.is_some()
                    && (row.parent_uuid == Some(invocation.uuid.as_str())
                        || row.parent_uuid == invocation.last_uuid.as_deref());
                if !chained {
                    return None;
                }
                let bytes = local_command_output_bytes(row.text);
                if row.text.trim_start().starts_with("<local-command-stderr>") {
                    if invocation.stderr_event_uid.is_none() {
                        invocation.stderr_event_uid = Some(row.event_uid.to_string());
                        invocation.stderr_bytes = Some(bytes);
                    }
                } else if invocation.output_event_uid.is_none() {
                    invocation.output_event_uid = Some(row.event_uid.to_string());
                    invocation.stdout_bytes = Some(bytes);
                }
                invocation.last_uuid = Some(row.uuid.to_string());
                Some(invocation.marker())
            }
            _ => None,
        }
    }
}

impl PendingInvocation {
    fn marker(&self) -> SlashCommandMarker {
        let string = |value: &Option<String>| {
            value
                .as_deref()
                .map(|text| Value::String(text.to_string()))
                .unwrap_or(Value::Null)
        };
        let count = |value: &Option<usize>| value.map(Value::from).unwrap_or(Value::Null);
        SlashCommandMarker {
            marker_uid: format!("{}:{SLASH_COMMAND_MARKER_KIND}", self.uuid),
            message_id: self.uuid.clone(),
            // The invocation's own parent, which is the caveat exactly when
            // the triad is chained.
            parent_id: self.parent_uuid.clone(),
            ts_ms: self.ts_ms,
            payload: vec![
                ("command_name", string(&self.fields.command_name)),
                ("command_message", string(&self.fields.command_message)),
                ("command_args", string(&self.fields.command_args)),
                ("command_mode", string(&self.command_mode)),
                ("origin_kind", string(&self.origin_kind)),
                ("attachment_type", string(&self.attachment_type)),
                ("caveat_event_uid", string(&self.caveat_event_uid)),
                (
                    "invocation_event_uid",
                    Value::String(self.event_uid.clone()),
                ),
                ("output_event_uid", string(&self.output_event_uid)),
                ("stdout_bytes", count(&self.stdout_bytes)),
                ("stderr_event_uid", string(&self.stderr_event_uid)),
                ("stderr_bytes", count(&self.stderr_bytes)),
            ],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn payload_field<'a>(marker: &'a SlashCommandMarker, name: &str) -> &'a Value {
        marker
            .payload
            .iter()
            .find(|(field, _)| *field == name)
            .map(|(_, value)| value)
            .unwrap_or(&Value::Null)
    }

    /// The stored vocabulary, spelled exactly as the issue that introduced
    /// it and as the column documentation names it.
    #[test]
    fn the_stored_spellings_are_the_documented_vocabulary() {
        let spellings: Vec<&str> = ControlKind::ALL.iter().map(|kind| kind.as_str()).collect();
        assert_eq!(
            spellings,
            [
                "slash_command_caveat",
                "slash_command_invocation",
                "slash_command_output",
                "task_notification",
                "hook_output",
                "bash_passthrough_input",
                "bash_passthrough_output",
                "system_reminder",
                "codex_context_wrapper",
                "meta",
                "resume_marker",
            ]
        );
        for kind in ControlKind::ALL {
            assert_eq!(ControlKind::parse(kind.as_str()), Some(*kind));
        }
        assert_eq!(ControlKind::parse("prompt"), None);
        assert_eq!(ControlKind::parse("Meta"), None);
    }

    #[test]
    fn wrappers_are_classified_by_the_tag_they_open_with() {
        let cases = [
            (
                "Caveat: The messages below were generated by the user while running local commands. DO NOT respond",
                ControlKind::SlashCommandCaveat,
            ),
            (
                "<command-message>review is running…</command-message>\n<command-name>/review</command-name>",
                ControlKind::SlashCommandInvocation,
            ),
            ("<command-name>/init</command-name>", ControlKind::SlashCommandInvocation),
            ("<command-args>--fix</command-args>", ControlKind::SlashCommandInvocation),
            ("<local-command-stdout>ok</local-command-stdout>", ControlKind::SlashCommandOutput),
            ("<local-command-stderr>no</local-command-stderr>", ControlKind::SlashCommandOutput),
            ("<task-notification>bash_1 done</task-notification>", ControlKind::TaskNotification),
            ("<bash-input>ls</bash-input>", ControlKind::BashPassthroughInput),
            ("<bash-stdout>a b</bash-stdout>", ControlKind::BashPassthroughOutput),
            ("<bash-stderr>oops</bash-stderr>", ControlKind::BashPassthroughOutput),
            ("<user-prompt-submit-hook>lint ok</user-prompt-submit-hook>", ControlKind::HookOutput),
            ("<session-start-hook>hi</session-start-hook>", ControlKind::HookOutput),
            ("/resume 1111", ControlKind::ResumeMarker),
            ("/Continue", ControlKind::ResumeMarker),
            ("  <command-name>/x</command-name>", ControlKind::SlashCommandInvocation),
        ];
        for (text, expected) in cases {
            assert_eq!(claude_text_control_kind(text), Some(expected), "{text}");
        }
        for prompt in [
            "please fix the build",
            "run /review on this",
            "mentions <command-name> later",
            "/resumed the work yesterday",
            "<b>bold</b>",
            "",
        ] {
            assert_eq!(claude_text_control_kind(prompt), None, "{prompt}");
        }
    }

    #[test]
    fn a_task_notification_is_recognised_by_any_of_its_three_signals() {
        let by_origin = json!({"origin": {"kind": "task-notification"}});
        let by_attachment =
            json!({"attachment": {"type": "queued_command", "commandMode": "task-notification"}});
        let by_text = json!({});
        assert_eq!(
            claude_record_control_kind(by_origin.as_object().unwrap(), "anything"),
            Some(ControlKind::TaskNotification)
        );
        assert_eq!(
            claude_record_control_kind(by_attachment.as_object().unwrap(), "anything"),
            Some(ControlKind::TaskNotification)
        );
        assert_eq!(
            claude_record_control_kind(
                by_text.as_object().unwrap(),
                "<task-notification>done</task-notification>"
            ),
            Some(ControlKind::TaskNotification)
        );
        assert_eq!(
            claude_record_control_kind(by_text.as_object().unwrap(), "fix it"),
            None
        );
    }

    #[test]
    fn meta_is_the_fallback_not_the_first_answer() {
        let meta = json!({"isMeta": true});
        let obj = meta.as_object().unwrap();
        assert_eq!(
            claude_record_control_kind(obj, "<command-name>/init</command-name>"),
            Some(ControlKind::SlashCommandInvocation)
        );
        assert_eq!(
            claude_record_control_kind(obj, "bookkeeping"),
            Some(ControlKind::Meta)
        );
        // Nothing but reminders: the reminders are the rows, and there is no
        // meta text left to store.
        assert_eq!(claude_record_control_kind(obj, ""), None);
    }

    #[test]
    fn system_reminders_are_split_from_the_prompt_verbatim() {
        let split = split_system_reminders(
            "<system-reminder>\nbe brief\n</system-reminder>\nfix the build\n<system-reminder>x</system-reminder>",
        );
        assert_eq!(split.prompt, "fix the build");
        assert_eq!(
            split.reminders,
            vec![
                "<system-reminder>\nbe brief\n</system-reminder>".to_string(),
                "<system-reminder>x</system-reminder>".to_string(),
            ]
        );

        let only = split_system_reminders("<system-reminder>a</system-reminder>");
        assert_eq!(only.prompt, "");
        assert_eq!(only.reminders.len(), 1);

        let none = split_system_reminders("plain prompt");
        assert_eq!(none.prompt, "plain prompt");
        assert!(none.reminders.is_empty());

        let unterminated = split_system_reminders("hi <system-reminder>never closed");
        assert_eq!(unterminated.prompt, "hi");
        assert_eq!(
            unterminated.reminders,
            vec!["<system-reminder>never closed".to_string()]
        );
    }

    #[test]
    fn slash_command_fields_are_read_in_any_order() {
        let fields = parse_slash_command(
            "<command-message>review is running…</command-message>\n<command-name>/review</command-name>\n<command-args>--strict</command-args>",
        );
        assert_eq!(fields.command_name.as_deref(), Some("/review"));
        assert_eq!(
            fields.command_message.as_deref(),
            Some("review is running…")
        );
        assert_eq!(fields.command_args.as_deref(), Some("--strict"));
        let bare = parse_slash_command("<command-name>/init</command-name>");
        assert_eq!(bare.command_args, None);
        assert_eq!(bare.command_message, None);
    }

    #[test]
    fn output_bytes_exclude_the_wrapper() {
        assert_eq!(
            local_command_output_bytes(
                "<local-command-stdout>review summary: no issues</local-command-stdout>"
            ),
            "review summary: no issues".len()
        );
        assert_eq!(
            local_command_output_bytes("<local-command-stderr>é</local-command-stderr>"),
            2
        );
        assert_eq!(local_command_output_bytes("bare"), 4);
    }

    /// The triad as Claude Code writes it: caveat, invocation, output, each
    /// the parent of the next. burn's `slash_triads` collapses exactly this
    /// chain; the marker has to carry everything its classifier reads.
    #[test]
    fn a_chained_triad_becomes_one_marker_naming_all_three_rows() {
        let mut triads = SlashCommandTriads::default();
        let caveat = ControlRow {
            session_id: "s",
            uuid: "cav",
            parent_uuid: Some("asst"),
            event_uid: "cav:0",
            ts_ms: 1,
            kind: ControlKind::SlashCommandCaveat,
            text: CLAUDE_CAVEAT_PREFIX,
            origin_kind: None,
            command_mode: None,
            attachment_type: None,
        };
        assert_eq!(triads.observe(&caveat), None);
        let invocation = ControlRow {
            session_id: "s",
            uuid: "inv",
            parent_uuid: Some("cav"),
            event_uid: "inv:0",
            ts_ms: 2,
            kind: ControlKind::SlashCommandInvocation,
            text: "<command-message>review is running…</command-message>\n<command-name>/review</command-name>",
            origin_kind: Some("user"),
            command_mode: Some("slash"),
            attachment_type: None,
        };
        let opened = triads
            .observe(&invocation)
            .expect("the invocation opens the marker");
        assert_eq!(opened.marker_uid, "inv:slash_command");
        assert_eq!(opened.message_id, "inv");
        assert_eq!(opened.parent_id.as_deref(), Some("cav"));
        assert_eq!(opened.ts_ms, 2);
        assert_eq!(payload_field(&opened, "command_name"), "/review");
        assert_eq!(payload_field(&opened, "caveat_event_uid"), "cav:0");
        assert_eq!(payload_field(&opened, "invocation_event_uid"), "inv:0");
        assert_eq!(payload_field(&opened, "output_event_uid"), &Value::Null);
        assert_eq!(payload_field(&opened, "origin_kind"), "user");
        assert_eq!(payload_field(&opened, "command_mode"), "slash");

        let output = ControlRow {
            session_id: "s",
            uuid: "out",
            parent_uuid: Some("inv"),
            event_uid: "out:0",
            ts_ms: 3,
            kind: ControlKind::SlashCommandOutput,
            text: "<local-command-stdout>review summary: no issues</local-command-stdout>",
            origin_kind: None,
            command_mode: None,
            attachment_type: None,
        };
        let closed = triads
            .observe(&output)
            .expect("the output extends the marker");
        assert_eq!(closed.marker_uid, opened.marker_uid);
        assert_eq!(payload_field(&closed, "output_event_uid"), "out:0");
        assert_eq!(payload_field(&closed, "stdout_bytes"), 25);
        assert_eq!(payload_field(&closed, "command_name"), "/review");

        // A stderr row chained onto the stdout row belongs to the same command.
        let stderr = ControlRow {
            uuid: "err",
            parent_uuid: Some("out"),
            event_uid: "err:0",
            ts_ms: 4,
            text: "<local-command-stderr>warn</local-command-stderr>",
            ..output
        };
        let with_stderr = triads.observe(&stderr).unwrap();
        assert_eq!(payload_field(&with_stderr, "output_event_uid"), "out:0");
        assert_eq!(payload_field(&with_stderr, "stderr_event_uid"), "err:0");
        assert_eq!(payload_field(&with_stderr, "stderr_bytes"), 4);
    }

    /// An invocation whose parent is not the caveat is still a command, just
    /// one whose caveat the marker cannot vouch for; an output row that hangs
    /// off nothing pending is stored on its own and grouped with nothing.
    #[test]
    fn an_unchained_row_is_not_grouped() {
        let mut triads = SlashCommandTriads::default();
        let invocation = ControlRow {
            session_id: "s",
            uuid: "inv",
            parent_uuid: Some("elsewhere"),
            event_uid: "inv:0",
            ts_ms: 2,
            kind: ControlKind::SlashCommandInvocation,
            text: "<command-name>/init</command-name>",
            origin_kind: None,
            command_mode: None,
            attachment_type: None,
        };
        let marker = triads.observe(&invocation).unwrap();
        assert_eq!(payload_field(&marker, "caveat_event_uid"), &Value::Null);
        assert_eq!(marker.parent_id.as_deref(), Some("elsewhere"));

        let orphan = ControlRow {
            uuid: "out",
            parent_uuid: Some("someone-else"),
            event_uid: "out:0",
            kind: ControlKind::SlashCommandOutput,
            text: "<local-command-stdout>x</local-command-stdout>",
            ..invocation
        };
        assert_eq!(triads.observe(&orphan), None);

        let other_session = ControlRow {
            session_id: "other",
            uuid: "out2",
            parent_uuid: Some("inv"),
            ..orphan
        };
        assert_eq!(triads.observe(&other_session), None);
    }

    /// Two commands back to back: the second caveat opens a new triad and the
    /// first command's marker is left as it was.
    #[test]
    fn consecutive_commands_do_not_share_a_marker() {
        let mut triads = SlashCommandTriads::default();
        let row = |uuid: &'static str,
                   parent: &'static str,
                   kind: ControlKind,
                   text: &'static str| ControlRow {
            session_id: "s",
            uuid,
            parent_uuid: Some(parent),
            event_uid: uuid,
            ts_ms: 1,
            kind,
            text,
            origin_kind: None,
            command_mode: None,
            attachment_type: None,
        };
        triads.observe(&row(
            "c1",
            "a0",
            ControlKind::SlashCommandCaveat,
            CLAUDE_CAVEAT_PREFIX,
        ));
        let first = triads
            .observe(&row(
                "i1",
                "c1",
                ControlKind::SlashCommandInvocation,
                "<command-name>/review</command-name>",
            ))
            .unwrap();
        triads.observe(&row(
            "o1",
            "i1",
            ControlKind::SlashCommandOutput,
            "<local-command-stdout>a</local-command-stdout>",
        ));
        triads.observe(&row(
            "c2",
            "a1",
            ControlKind::SlashCommandCaveat,
            CLAUDE_CAVEAT_PREFIX,
        ));
        let second = triads
            .observe(&row(
                "i2",
                "c2",
                ControlKind::SlashCommandInvocation,
                "<command-name>/init</command-name>",
            ))
            .unwrap();
        assert_ne!(first.marker_uid, second.marker_uid);
        assert_eq!(payload_field(&second, "command_name"), "/init");
        assert_eq!(payload_field(&second, "caveat_event_uid"), "c2");
        // The first command's output must not be attributed to the second.
        assert_eq!(payload_field(&second, "output_event_uid"), &Value::Null);
    }

    /// The pending state is what a resumed pass restores, so it has to
    /// survive serialization exactly.
    #[test]
    fn pending_state_round_trips_through_serde() {
        let mut triads = SlashCommandTriads::default();
        triads.observe(&ControlRow {
            session_id: "s",
            uuid: "inv",
            parent_uuid: None,
            event_uid: "inv:0",
            ts_ms: 2,
            kind: ControlKind::SlashCommandInvocation,
            text: "<command-name>/review</command-name>",
            origin_kind: None,
            command_mode: None,
            attachment_type: None,
        });
        let encoded = serde_json::to_string(&triads).unwrap();
        let decoded: SlashCommandTriads = serde_json::from_str(&encoded).unwrap();
        assert_eq!(decoded, triads);
        assert!(SlashCommandTriads::default().is_empty());
        assert!(!decoded.is_empty());
    }
}
