/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function historyDelivery(requestJson: string, dbPath?: string | undefined | null): Promise<string>
/**
 * One bounded drain of every selected delivery job, run by the single generic
 * Rust worker. `prepare` and `send` are the registered JavaScript destinations;
 * `cancelled` reports a host stop request. None of them ever rejects.
 */
export declare function historyDeliveryDrain(optionsJson: string, dbPath: string | undefined | null, prepare: (arg: string) => any, send: (arg: string) => any, cancelled: () => any): Promise<string>
export declare function getSourceObservation(requestJson: string): Promise<string>
export declare function applySourceObservations(requestJson: string): Promise<string>
export declare function applySourceEvidence(requestJson: string): Promise<string>
/** Contract version implemented by this native addon. */
export declare function nativeContractVersion(): number
/**
 * Optimization profile this addon was compiled with: `release` or `debug`.
 * Performance measurements are only meaningful against `release`.
 */
export declare function nativeBuildProfile(): string
export interface HistoryQueryOptions {
  scope?: string
  dbPath?: string
  source?: string
  project?: string
  tag?: string
  beforeMs?: number
  limit?: number
}
export interface SearchOptions {
  scope?: string
  dbPath?: string
  source?: string
  project?: string
  tag?: string
  beforeMs?: number
  limit?: number
  rawFts?: boolean
}
export interface SessionOptions {
  dbPath?: string
  source?: string
  tag?: string
}
export interface NativeHistoryEntry {
  id: number
  source: string
  sessionId?: string
  project?: string
  prompt: string
  timestampMs: number
  locations: Array<string>
}
export interface NativeSessionEvent {
  id: number
  source: string
  sessionId: string
  project?: string
  /** Canonical project identity, denormalized from the owning session. */
  projectKey?: string
  cwd?: string
  gitBranch?: string
  messageId?: string
  parentId?: string
  tsMs: number
  role: string
  kind: string
  text?: string
  model?: string
  tokenJson?: string
  /**
   * The upstream inference provider the harness named, when it names one
   * (OpenCode's `providerID`). Null elsewhere rather than inferred.
   */
  provider?: string
  eventUid: string
  /**
   * Per-tool-result fidelity. Null on every row that is not a tool result,
   * and on a tool-result row whose provider does not record the fact.
   */
  toolUseId?: string
  /** Raw UTF-8 byte length of the provider's result payload. */
  payloadBytes?: number
  /** True when the harness had already truncated the payload. */
  payloadTruncated?: boolean
  /** First 16 hex characters of the payload's sha256. */
  payloadHash?: string
  /** n-th result recorded for this `toolUseId`, from zero. */
  callIndex?: number
  /** Position of this result in the transcript's tool-result order. */
  eventIndex?: number
  /** `running` / `completed` / `errored` / `cancelled` / `unknown`. */
  resultStatus?: string
  /** `tool_result` / `subagent_notification` / `function_call_output`. */
  eventSource?: string
  /** Which provider signal set the error. */
  errorSignal?: string
  subagentSessionId?: string
  agentId?: string
  requestId?: string
  /** Why the turn ended, as the harness reported it. */
  stopReason?: string
  agentVersion?: string
  isSidechain?: boolean
  isMeta?: boolean
  turnId?: string
}
export interface EventCursor {
  tsMs: number
  id: number
}
export interface EventsPageOptions {
  dbPath?: string
  source?: string
  limit?: number
  after?: EventCursor
}
export interface SessionEventsPage {
  events: Array<NativeSessionEvent>
  nextCursor?: EventCursor
}
export interface NativeSessionToolCall {
  id: number
  source: string
  sessionId: string
  messageId?: string
  toolUseId: string
  name: string
  target?: string
  /**
   * Stored provider arguments, unparsed. The SDK owns JSON parsing so an
   * unreadable value cannot fail a whole page at the boundary.
   */
  argsJson?: string
  isError?: boolean
  tsMs?: number
}
export interface NativeSessionFileEdit {
  id: number
  source: string
  sessionId: string
  messageId?: string
  toolUseId: string
  filePath: string
  toolName?: string
  linesAdded?: number
  linesRemoved?: number
  /** Stored provider patch, unparsed, for the same reason as `args_json`. */
  structuredPatchJson?: string
  userModified?: boolean
  tsMs?: number
  gitBranch?: string
  cwd?: string
}
/**
 * Continuation for tool call and file edit pages. `tsMs` is optional because
 * both tables order their undated rows last.
 *
 * Absent-or-`undefined` is how a caller says "inside the undated tail": an
 * explicit JavaScript `null` cannot be converted to `i64` and fails at the
 * boundary, so the SDK normalizes `null` to `undefined` before calling in.
 */
export interface EvidenceCursor {
  tsMs?: number
  id: number
}
export interface EvidencePageOptions {
  dbPath?: string
  limit?: number
  after?: EvidenceCursor
}
export interface NativeSessionUserTurnBlock {
  /** `text` or `tool_result`. */
  kind: string
  toolUseId?: string
  /**
   * Measured payload bytes when the parser recorded them, otherwise the
   * UTF-8 length of the stored text.
   */
  byteLen: number
  /**
   * True when the result is known to have failed, false when it is known
   * to have succeeded, null when the provider has not said.
   */
  isError?: boolean
}
export interface NativeSessionUserTurn {
  id: number
  source: string
  sessionId: string
  messageId?: string
  /**
   * The nearest messages recorded either side of this turn, from either
   * side of the conversation. Null only when the session recorded no named
   * message on that side; an event the provider left unnamed is passed
   * over rather than nulling the field.
   */
  precedingMessageId?: string
  followingMessageId?: string
  tsMs: number
  blocks: Array<NativeSessionUserTurnBlock>
}
export interface UserTurnsPageOptions {
  dbPath?: string
  limit?: number
  after?: EventCursor
}
export interface SessionUserTurnsPage {
  contractVersion: number
  source: string
  sessionId: string
  userTurns: Array<NativeSessionUserTurn>
  nextCursor?: EventCursor
}
export interface SessionToolCallsPage {
  contractVersion: number
  source: string
  sessionId: string
  toolCalls: Array<NativeSessionToolCall>
  nextCursor?: EvidenceCursor
}
export interface SessionFileEditsPage {
  contractVersion: number
  source: string
  sessionId: string
  fileEdits: Array<NativeSessionFileEdit>
  nextCursor?: EvidenceCursor
}
/**
 * Normalized usage for one request or one session.
 *
 * The optional fields stay optional across the boundary: `null` means the
 * provider did not report that counter, which is a different fact from a
 * reported zero and the only thing that makes `coverage` interpretable.
 */
export interface NativeNormalizedUsage {
  inputTokens: number
  outputTokens: number
  reasoningTokens?: number
  cacheReadTokens: number
  cacheWriteTokens: number
  cacheWrite5mTokens?: number
  cacheWrite1hTokens?: number
  providerTotalTokens?: number
  reportedCostUsd?: number
  /**
   * `per-request`, `per-message`, `cumulative-delta`, `context-proxy`, or
   * `mixed` on a summary spanning more than one.
   */
  accounting: string
  hasInputTokens: boolean
  hasOutputTokens: boolean
  hasReasoningTokens: boolean
  hasCacheReadTokens: boolean
  hasCacheWriteTokens: boolean
}
export interface NativeSessionRequest {
  id: number
  source: string
  sessionId: string
  requestKey: string
  /** `request-id`, `provider-message-id`, `request-span` or `record-id`. */
  requestKeySource: string
  messageIds: Array<string>
  model?: string
  provider?: string
  firstTsMs: number
  lastTsMs: number
  /**
   * Absent when the request carried no usage evidence, or when the
   * evidence could not be trusted — `diagnostics` says which.
   */
  usage?: NativeNormalizedUsage
  usageError?: string
  toolUseIds: Array<string>
  hasThinking: boolean
  eventCount: number
  diagnostics: Array<string>
}
export interface RequestCursor {
  tsMs: number
  id: number
}
export interface RequestPageOptions {
  dbPath?: string
  limit?: number
  after?: RequestCursor
}
export interface SessionRequestsPage {
  contractVersion: number
  source: string
  sessionId: string
  requests: Array<NativeSessionRequest>
  nextCursor?: RequestCursor
}
export interface SessionUsageOptions {
  dbPath?: string
}
/**
 * One session's usage rollup. `usage` is absent when the session has no
 * usage evidence at all — not zeroed, because zero is a claim.
 */
export interface SessionUsage {
  contractVersion: number
  source: string
  sessionId: string
  usage?: NativeNormalizedUsage
  /** Requests that contributed to `usage`. */
  requestCount: number
  /** Requests seen, including ones with no usage. */
  totalRequestCount: number
  /**
   * Every accounting mode present. More than one means the totals mix
   * units and should be read per mode.
   */
  accounting: Array<string>
  models: Array<string>
  firstTsMs?: number
  lastTsMs?: number
  diagnostics: Array<string>
  /** The totals exceeded what can be represented and must not be used. */
  overflowed: boolean
}
export interface SourceCount {
  source: string
  count: number
}
export interface ProjectCount {
  project: string
  count: number
}
export interface NativeStats {
  scope: string
  total: number
  bySource: Array<SourceCount>
  byProject: Array<ProjectCount>
  /**
   * Which key `by_project` is bucketed by: `project_key` or `cwd`. Read it
   * rather than assuming -- the two produce different counts for the same
   * database.
   */
  groupedBy: string
  firstTimestampMs?: number
  lastTimestampMs?: number
}
export interface StatsOptions {
  scope?: string
  dbPath?: string
  tag?: string
  /**
   * Bucket `by_project` by the raw working directory instead of the
   * canonical project key. Defaults to false.
   */
  byCwd?: boolean
}
/** Full-text search of indexed history. Never discovers or syncs implicitly. */
export declare function search(query: string, options?: SearchOptions | undefined | null): Promise<Array<NativeHistoryEntry>>
/** Recent indexed history. Never discovers or syncs implicitly. */
export declare function recent(options?: HistoryQueryOptions | undefined | null): Promise<Array<NativeHistoryEntry>>
/** Indexed prompts for one session. Event payloads are separately paginated. */
export declare function getSession(sessionId: string, options?: SessionOptions | undefined | null): Promise<Array<NativeHistoryEntry>>
/** One bounded page of normalized events for a session. */
export declare function getSessionEventsPage(sessionId: string, options?: EventsPageOptions | undefined | null): Promise<SessionEventsPage>
/**
 * One bounded page of recorded tool calls for one session.
 *
 * Both `source` and `sessionId` are required: provider session ids are not
 * globally unique, so an id-only lookup could interleave two sessions.
 */
export declare function getSessionToolCallsPage(source: string, sessionId: string, options?: EvidencePageOptions | undefined | null): Promise<SessionToolCallsPage>
/**
 * One bounded page of user turns for one session, oldest first.
 *
 * Each turn carries the ordered blocks the provider attached to one user
 * message: the human's own text and the tool results that came back with it,
 * with the measured payload size of each. Computed from `session_events`
 * rather than a table of its own, so it cannot disagree with the transcript.
 */
export declare function getSessionUserTurnsPage(source: string, sessionId: string, options?: UserTurnsPageOptions | undefined | null): Promise<SessionUserTurnsPage>
/** One bounded page of recorded file edits for one session. */
export declare function getSessionFileEditsPage(source: string, sessionId: string, options?: EvidencePageOptions | undefined | null): Promise<SessionFileEditsPage>
/**
 * One bounded page of a session's model requests, oldest first.
 *
 * Both halves of the identity are required for the same reason the evidence
 * pages require them: provider session ids collide across providers.
 */
export declare function getSessionRequestsPage(source: string, sessionId: string, options?: RequestPageOptions | undefined | null): Promise<SessionRequestsPage>
/** Provider-neutral usage rollup for one session. */
export declare function getSessionUsage(source: string, sessionId: string, options?: SessionUsageOptions | undefined | null): Promise<SessionUsage>
/** Database statistics over already-indexed data. */
export declare function stats(options?: StatsOptions | undefined | null): Promise<NativeStats>
export interface CatalogSession {
  source: string
  sessionId: string
  cwd?: string
  gitBranch?: string
  firstActivityMs?: number
  lastActivityMs?: number
  firstPrompt?: string
  lastAssistantText?: string
  models: Array<string>
  originator?: string
  agentVersion?: string
  repoUrl?: string
  initialCommit?: string
  workspaceRoots: Array<string>
  rawPath?: string
  sourceStamp?: string
  discoveryState: string
  /**
   * Canonical project identity: `host/owner/repo`, or the working
   * directory when no git remote resolves.
   */
  projectKey?: string
  /** `remote`, `path`, or `inherited`. */
  projectKeyMethod?: string
  locations: Array<string>
  fromCache: boolean
}
export interface CatalogCursor {
  lastActivityMs?: number
  source: string
  sessionId: string
}
export interface ListCatalogOptions {
  scope?: string
  dbPath?: string
  sources?: Array<string>
  limit?: number
  beforeMs?: number
  after?: CatalogCursor
  /**
   * Exact canonical project key (`host/owner/repo`, or the working
   * directory when the checkout has no remote).
   */
  projectKey?: string
}
export interface SessionCatalogPage {
  contractVersion: number
  scope: string
  sessions: Array<CatalogSession>
  nextCursor?: CatalogCursor
}
/** Cache-only indexed catalog query. Missing databases return an empty page. */
export declare function listSessionCatalogPage(options?: ListCatalogOptions | undefined | null): Promise<SessionCatalogPage>
/** Convenience first-page catalog listing with identical cache-only semantics. */
export declare function listSessionCatalog(options?: ListCatalogOptions | undefined | null): Promise<Array<CatalogSession>>
export interface DiscoverOptions {
  sourceConnectors?: Array<string>
  scope?: string
  dbPath?: string
  sources?: Array<string>
  limit?: number
}
export interface DiscoveryDiagnostic {
  source: string
  locator?: string
  error: string
}
export interface ProviderSummary {
  source: string
  candidates: number
  discovered: number
  skippedUnchanged: number
  failed: boolean
}
export interface DiscoveryCounters {
  candidatesEnumerated: number
  shallowReads: number
  skippedUnchanged: number
  filesOpened: number
  bytesRead: number
  providerQueries: number
  recordsInspected: number
}
export interface SourceExemption {
  source: string
  reason: string
}
export interface DiscoverResult {
  contractVersion: number
  scope: string
  locationsRun: Array<string>
  sessions: Array<CatalogSession>
  discovered: number
  skippedUnchanged: number
  providers: Array<ProviderSummary>
  exemptSources: Array<SourceExemption>
  diagnostics: Array<DiscoveryDiagnostic>
  counters: DiscoveryCounters
}
/** Explicit bounded provider discovery. It updates only the session catalog. */
export declare function discoverSessions(options?: DiscoverOptions | undefined | null): Promise<DiscoverResult>
export interface HydrateSessionOptions {
  sourceConnectors?: Array<string>
  source: string
  sessionId: string
  scope?: string
  dbPath?: string
  includeRelated?: boolean
}
export interface HydrationIndexedThrough {
  sourceStamp?: string
  lastEventAtMs?: number
}
export interface HydrationEvidence {
  prompts: number
  events: number
  toolCalls: number
  fileEdits: number
  relatedSessions: number
}
export interface HydrationDiagnostic {
  code: string
  message: string
  durationMs?: number
  sourceBytes?: number
  recordsParsed?: number
}
export interface HydrateSessionResult {
  contractVersion: number
  source: string
  sessionId: string
  status: string
  capability: string
  discoveryState: string
  presence: string
  indexedThrough: HydrationIndexedThrough
  evidence: HydrationEvidence
  /**
   * Bytes read from provider files by this hydration. About the size of
   * the append when a live transcript grew, and small but **not zero** when
   * the session was unchanged: deciding nothing changed means validating
   * each cursor against a bounded window of the file it was written from.
   * Zero is reserved for a pass that opened no provider file at all.
   */
  bytesRead: number
  /**
   * Evidence kinds this hydration can have indexed, as wire names
   * (`history`, `session_event`, `tool_call`, `file_edit`,
   * `relationship`, `commit_link`).
   */
  coverage: Array<string>
  relatedSessionIds: Array<string>
  diagnostics: Array<HydrationDiagnostic>
}
/** Fully index one cataloged session without enumerating unrelated sessions. */
export declare function hydrateSession(options: HydrateSessionOptions): Promise<HydrateSessionResult>
export interface NativeSessionRelationship {
  source: string
  parentSessionId: string
  childSessionId?: string
  relationship: string
  identityStatus: string
  childAgentType?: string
  childAgentName?: string
  childModel?: string
  spawnDepth?: number
  evidenceKind: string
  evidenceLocator?: string
  evidenceRef?: string
  childHasEvents: boolean
  spawnedAtMs?: number
  createdMs: number
  relationshipUid: string
  originSessionId?: string
}
export interface NativeRelationshipCapabilities {
  source: string
  stableChildIdentity: string
  recordsAgentType: boolean
  recordsSpawnTime: boolean
  recordsEvidenceLocator: boolean
}
export interface NativeRelationshipDiagnostic {
  code: string
  message: string
  relationshipUid?: string
}
export interface NativeSessionRelationships {
  contractVersion: number
  source: string
  sessionId: string
  asParent: Array<NativeSessionRelationship>
  asChild: Array<NativeSessionRelationship>
  continuity: Array<NativeSessionRelationship>
  capabilities: NativeRelationshipCapabilities
  diagnostics: Array<NativeRelationshipDiagnostic>
}
export interface NativeSessionTreeNode {
  source: string
  sessionId: string
  depth: number
  parentSessionId?: string
  relationship?: NativeSessionRelationship
  childCount: number
  hasEvents: boolean
  truncated: boolean
}
export interface NativeSessionTree {
  contractVersion: number
  source: string
  rootSessionId: string
  nodes: Array<NativeSessionTreeNode>
  unlinked: Array<NativeSessionRelationship>
  capabilities: NativeRelationshipCapabilities
  diagnostics: Array<NativeRelationshipDiagnostic>
  truncated: boolean
  maxDepthReached: number
}
export interface RelationshipCursor {
  spawnedAtMs?: number
  relationshipUid: string
}
export interface NativeSessionChildrenPage {
  children: Array<NativeSessionRelationship>
  nextCursor?: RelationshipCursor
}
export interface RelationshipOptions {
  source: string
  sessionId: string
  dbPath?: string
}
export interface SessionTreeOptions {
  source: string
  sessionId: string
  dbPath?: string
  maxDepth?: number
  maxNodes?: number
  /**
   * Which edges the walk follows. Omitted means delegation only, which is
   * what every caller got before continuity existed.
   */
  relationshipKinds?: Array<string>
}
export interface SessionChildrenPageOptions {
  source: string
  sessionId: string
  dbPath?: string
  limit?: number
  after?: RelationshipCursor
  relationshipKinds?: Array<string>
}
/**
 * Direct delegation relationships for one session, in both directions.
 * A missing database is an empty result, not an error.
 */
export declare function getSessionRelationships(options: RelationshipOptions): Promise<NativeSessionRelationships>
/**
 * The complete descendant delegation tree for one session: pre-order,
 * cycle-safe, and bounded by `maxDepth` / `maxNodes`.
 */
export declare function getSessionTree(options: SessionTreeOptions): Promise<NativeSessionTree>
/**
 * One bounded page of a session's direct children, in the same total order
 * the tree traversal uses.
 */
export declare function getSessionChildrenPage(options: SessionChildrenPageOptions): Promise<NativeSessionChildrenPage>
export interface SyncOptions {
  sourceConnectors?: Array<string>
  dbPath?: string
  scope?: string
}
export interface SyncResult {
  databasePath: string
  completed: boolean
  scope: string
}
/** Explicit full ingestion. A read operation never calls this implicitly. */
export declare function sync(options?: SyncOptions | undefined | null): Promise<SyncResult>
/** Backward-compatible internal capture entry point; not used by the SDK. */
export declare function syncLocal(): Promise<void>
export declare function installGitHooks(optionsJson: string, node: string, sdkUrl: string): Promise<string>
export declare function linkGitCommit(optionsJson: string): Promise<string>
