/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Contract version implemented by this native addon. */
export declare function nativeContractVersion(): number
/**
 * Optimization profile this addon was compiled with: `release` or `debug`.
 * Performance measurements are only meaningful against `release`.
 */
export declare function nativeBuildProfile(): string
export interface HistoryQueryOptions {
  scope?: string
  dbPath?: string
  source?: string
  project?: string
  tag?: string
  beforeMs?: number
  limit?: number
}
export interface SearchOptions {
  scope?: string
  dbPath?: string
  source?: string
  project?: string
  tag?: string
  beforeMs?: number
  limit?: number
  rawFts?: boolean
}
export interface SessionOptions {
  dbPath?: string
  source?: string
  tag?: string
}
export interface NativeHistoryEntry {
  id: number
  source: string
  sessionId?: string
  project?: string
  prompt: string
  timestampMs: number
  locations: Array<string>
}
export interface NativeSessionEvent {
  id: number
  source: string
  sessionId: string
  project?: string
  cwd?: string
  gitBranch?: string
  messageId?: string
  parentId?: string
  tsMs: number
  role: string
  kind: string
  text?: string
  model?: string
  tokenJson?: string
  eventUid: string
}
export interface EventCursor {
  tsMs: number
  id: number
}
export interface EventsPageOptions {
  dbPath?: string
  source?: string
  limit?: number
  after?: EventCursor
}
export interface SessionEventsPage {
  events: Array<NativeSessionEvent>
  nextCursor?: EventCursor
}
export interface NativeSessionToolCall {
  id: number
  source: string
  sessionId: string
  messageId?: string
  toolUseId: string
  name: string
  target?: string
  /**
   * Stored provider arguments, unparsed. The SDK owns JSON parsing so an
   * unreadable value cannot fail a whole page at the boundary.
   */
  argsJson?: string
  isError?: boolean
  tsMs?: number
}
export interface NativeSessionFileEdit {
  id: number
  source: string
  sessionId: string
  messageId?: string
  toolUseId: string
  filePath: string
  toolName?: string
  linesAdded?: number
  linesRemoved?: number
  /** Stored provider patch, unparsed, for the same reason as `args_json`. */
  structuredPatchJson?: string
  userModified?: boolean
  tsMs?: number
  gitBranch?: string
  cwd?: string
}
/**
 * Continuation for tool call and file edit pages. `tsMs` is optional because
 * both tables order their undated rows last.
 *
 * Absent-or-`undefined` is how a caller says "inside the undated tail": an
 * explicit JavaScript `null` cannot be converted to `i64` and fails at the
 * boundary, so the SDK normalizes `null` to `undefined` before calling in.
 */
export interface EvidenceCursor {
  tsMs?: number
  id: number
}
export interface EvidencePageOptions {
  dbPath?: string
  limit?: number
  after?: EvidenceCursor
}
export interface SessionToolCallsPage {
  contractVersion: number
  source: string
  sessionId: string
  toolCalls: Array<NativeSessionToolCall>
  nextCursor?: EvidenceCursor
}
export interface SessionFileEditsPage {
  contractVersion: number
  source: string
  sessionId: string
  fileEdits: Array<NativeSessionFileEdit>
  nextCursor?: EvidenceCursor
}
export interface SourceCount {
  source: string
  count: number
}
export interface ProjectCount {
  project: string
  count: number
}
export interface NativeStats {
  scope: string
  total: number
  bySource: Array<SourceCount>
  byProject: Array<ProjectCount>
  firstTimestampMs?: number
  lastTimestampMs?: number
}
export interface StatsOptions {
  scope?: string
  dbPath?: string
  tag?: string
}
/** Full-text search of indexed history. Never discovers or syncs implicitly. */
export declare function search(query: string, options?: SearchOptions | undefined | null): Promise<Array<NativeHistoryEntry>>
/** Recent indexed history. Never discovers or syncs implicitly. */
export declare function recent(options?: HistoryQueryOptions | undefined | null): Promise<Array<NativeHistoryEntry>>
/** Indexed prompts for one session. Event payloads are separately paginated. */
export declare function getSession(sessionId: string, options?: SessionOptions | undefined | null): Promise<Array<NativeHistoryEntry>>
/** One bounded page of normalized events for a session. */
export declare function getSessionEventsPage(sessionId: string, options?: EventsPageOptions | undefined | null): Promise<SessionEventsPage>
/**
 * One bounded page of recorded tool calls for one session.
 *
 * Both `source` and `sessionId` are required: provider session ids are not
 * globally unique, so an id-only lookup could interleave two sessions.
 */
export declare function getSessionToolCallsPage(source: string, sessionId: string, options?: EvidencePageOptions | undefined | null): Promise<SessionToolCallsPage>
/** One bounded page of recorded file edits for one session. */
export declare function getSessionFileEditsPage(source: string, sessionId: string, options?: EvidencePageOptions | undefined | null): Promise<SessionFileEditsPage>
/** Database statistics over already-indexed data. */
export declare function stats(options?: StatsOptions | undefined | null): Promise<NativeStats>
export interface CatalogSession {
  source: string
  sessionId: string
  cwd?: string
  gitBranch?: string
  firstActivityMs?: number
  lastActivityMs?: number
  firstPrompt?: string
  lastAssistantText?: string
  models: Array<string>
  originator?: string
  agentVersion?: string
  repoUrl?: string
  initialCommit?: string
  workspaceRoots: Array<string>
  rawPath?: string
  sourceStamp?: string
  discoveryState: string
  locations: Array<string>
  fromCache: boolean
}
export interface CatalogCursor {
  lastActivityMs?: number
  source: string
  sessionId: string
}
export interface ListCatalogOptions {
  scope?: string
  dbPath?: string
  sources?: Array<string>
  limit?: number
  beforeMs?: number
  after?: CatalogCursor
}
export interface SessionCatalogPage {
  contractVersion: number
  scope: string
  sessions: Array<CatalogSession>
  nextCursor?: CatalogCursor
}
/** Cache-only indexed catalog query. Missing databases return an empty page. */
export declare function listSessionCatalogPage(options?: ListCatalogOptions | undefined | null): Promise<SessionCatalogPage>
/** Convenience first-page catalog listing with identical cache-only semantics. */
export declare function listSessionCatalog(options?: ListCatalogOptions | undefined | null): Promise<Array<CatalogSession>>
export interface DiscoverOptions {
  scope?: string
  dbPath?: string
  sources?: Array<string>
  limit?: number
}
export interface DiscoveryDiagnostic {
  source: string
  locator?: string
  error: string
}
export interface ProviderSummary {
  source: string
  candidates: number
  discovered: number
  skippedUnchanged: number
  failed: boolean
}
export interface DiscoveryCounters {
  candidatesEnumerated: number
  shallowReads: number
  skippedUnchanged: number
  filesOpened: number
  bytesRead: number
  providerQueries: number
  recordsInspected: number
}
export interface SourceExemption {
  source: string
  reason: string
}
export interface DiscoverResult {
  contractVersion: number
  scope: string
  locationsRun: Array<string>
  sessions: Array<CatalogSession>
  discovered: number
  skippedUnchanged: number
  providers: Array<ProviderSummary>
  exemptSources: Array<SourceExemption>
  diagnostics: Array<DiscoveryDiagnostic>
  counters: DiscoveryCounters
}
/** Explicit bounded provider discovery. It updates only the session catalog. */
export declare function discoverSessions(options?: DiscoverOptions | undefined | null): Promise<DiscoverResult>
export interface HydrateSessionOptions {
  source: string
  sessionId: string
  scope?: string
  dbPath?: string
  includeRelated?: boolean
}
export interface HydrationIndexedThrough {
  sourceStamp?: string
  lastEventAtMs?: number
}
export interface HydrationEvidence {
  prompts: number
  events: number
  toolCalls: number
  fileEdits: number
  relatedSessions: number
}
export interface HydrationDiagnostic {
  code: string
  message: string
  durationMs?: number
  sourceBytes?: number
  recordsParsed?: number
}
export interface HydrateSessionResult {
  contractVersion: number
  source: string
  sessionId: string
  status: string
  capability: string
  discoveryState: string
  presence: string
  indexedThrough: HydrationIndexedThrough
  evidence: HydrationEvidence
  relatedSessionIds: Array<string>
  diagnostics: Array<HydrationDiagnostic>
}
/** Fully index one cataloged session without enumerating unrelated sessions. */
export declare function hydrateSession(options: HydrateSessionOptions): Promise<HydrateSessionResult>
export interface NativeSessionRelationship {
  source: string
  parentSessionId: string
  childSessionId?: string
  relationship: string
  identityStatus: string
  childAgentType?: string
  childAgentName?: string
  childModel?: string
  spawnDepth?: number
  evidenceKind: string
  evidenceLocator?: string
  evidenceRef?: string
  childHasEvents: boolean
  spawnedAtMs?: number
  createdMs: number
  relationshipUid: string
}
export interface NativeRelationshipCapabilities {
  source: string
  stableChildIdentity: string
  recordsAgentType: boolean
  recordsSpawnTime: boolean
  recordsEvidenceLocator: boolean
}
export interface NativeRelationshipDiagnostic {
  code: string
  message: string
  relationshipUid?: string
}
export interface NativeSessionRelationships {
  contractVersion: number
  source: string
  sessionId: string
  asParent: Array<NativeSessionRelationship>
  asChild: Array<NativeSessionRelationship>
  capabilities: NativeRelationshipCapabilities
  diagnostics: Array<NativeRelationshipDiagnostic>
}
export interface NativeSessionTreeNode {
  source: string
  sessionId: string
  depth: number
  parentSessionId?: string
  relationship?: NativeSessionRelationship
  childCount: number
  hasEvents: boolean
  truncated: boolean
}
export interface NativeSessionTree {
  contractVersion: number
  source: string
  rootSessionId: string
  nodes: Array<NativeSessionTreeNode>
  unlinked: Array<NativeSessionRelationship>
  capabilities: NativeRelationshipCapabilities
  diagnostics: Array<NativeRelationshipDiagnostic>
  truncated: boolean
  maxDepthReached: number
}
export interface RelationshipCursor {
  spawnedAtMs?: number
  relationshipUid: string
}
export interface NativeSessionChildrenPage {
  children: Array<NativeSessionRelationship>
  nextCursor?: RelationshipCursor
}
export interface RelationshipOptions {
  source: string
  sessionId: string
  dbPath?: string
}
export interface SessionTreeOptions {
  source: string
  sessionId: string
  dbPath?: string
  maxDepth?: number
  maxNodes?: number
}
export interface SessionChildrenPageOptions {
  source: string
  sessionId: string
  dbPath?: string
  limit?: number
  after?: RelationshipCursor
}
/**
 * Direct delegation relationships for one session, in both directions.
 * A missing database is an empty result, not an error.
 */
export declare function getSessionRelationships(options: RelationshipOptions): Promise<NativeSessionRelationships>
/**
 * The complete descendant delegation tree for one session: pre-order,
 * cycle-safe, and bounded by `maxDepth` / `maxNodes`.
 */
export declare function getSessionTree(options: SessionTreeOptions): Promise<NativeSessionTree>
/**
 * One bounded page of a session's direct children, in the same total order
 * the tree traversal uses.
 */
export declare function getSessionChildrenPage(options: SessionChildrenPageOptions): Promise<NativeSessionChildrenPage>
export interface SyncOptions {
  dbPath?: string
  scope?: string
}
export interface SyncResult {
  databasePath: string
  completed: boolean
  scope: string
}
/** Explicit full ingestion. A read operation never calls this implicitly. */
export declare function sync(options?: SyncOptions | undefined | null): Promise<SyncResult>
/** Backward-compatible internal capture entry point; not used by the SDK. */
export declare function syncLocal(): Promise<void>
export interface SyncPushResult {
  sent: number
  accepted: number
  authenticated: boolean
  syncSkipped: boolean
}
/** Cloud capture hook retained for Agent Relay integration. */
export declare function syncAndPush(): Promise<SyncPushResult>
export interface CloudOptions {
  dbPath?: string
  baseUrl?: string
  relayAccessToken?: string
  label?: string
}
export declare function accessToken(baseUrl?: string | undefined | null): Promise<string>
export interface ReplayOptions {
  baseUrl?: string
  limit?: number
  maxContent?: number
  json?: boolean
  out?: string
}
export interface ReplayResult {
  eventCount: number
  transcript?: string
  outputPath?: string
}
export declare function replay(sessionId: string, options?: ReplayOptions | undefined | null): Promise<ReplayResult>
export interface CloudAuth {
  baseUrl: string
  accessToken: string
  refreshToken?: string
}
export interface CloudPushResult {
  baseUrl: string
  sent: number
  accepted: number
  syncSkipped: boolean
}
export declare function cloudLoadAuth(baseUrl?: string | undefined | null): Promise<CloudAuth | null>
export declare function cloudLogin(options?: CloudOptions | undefined | null): Promise<CloudAuth>
export declare function enableCloud(options?: CloudOptions | undefined | null): Promise<CloudPushResult>
export declare function pushCloud(options?: CloudOptions | undefined | null): Promise<CloudPushResult>
export declare function installGitHooks(optionsJson: string, node: string, sdkUrl: string): Promise<string>
export declare function linkGitCommit(optionsJson: string): Promise<string>
export declare function createShareableTrace(sessionId: string, visibility: string, source?: string | undefined | null, baseUrl?: string | undefined | null): Promise<string>
