/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Result of one in-process sync+push. */
export interface SyncPushResult {
  sent: number
  accepted: number
  /** `false` when there's no stored relayhistory auth yet (a no-op, not an error). */
  authenticated: boolean
  /** `true` when another process owned the history scan; existing rows were still pushed. */
  syncSkipped: boolean
}
/** Refresh local history without reading auth or pushing to cloud. */
export declare function syncLocal(): Promise<void>
/**
 * Sync local agent history into the ai-hist DB, then push new records to
 * relayhistory-cloud. The blocking work (file/SQLite/HTTP) runs on a worker
 * thread so the Node event loop is never blocked.
 */
export declare function syncAndPush(): Promise<SyncPushResult>
