import { createHash } from "node:crypto";
import { URL } from "node:url";
import { readFile } from "node:fs/promises";
import { Hono } from "hono";
import {
  afterAll,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
  vi,
} from "vitest";
import type { AuthContext, HistoryEnv } from "../src/env.js";
import {
  acceptDelivery,
  canonicalJson,
  deliveryAccount,
  digest,
  expireBabysitterEvidence,
  listDelivery,
  parseDeliveryRequest,
  servicePayload,
  type DeliveryDb,
} from "../src/lib/delivery.js";
import { MAX_SCRUB_CHARS, scrubText } from "../src/lib/scrub.js";
import {
  DELIVERY_KINDS,
  MAX_DELIVERY_BYTES,
  MAX_DELIVERY_PAGE_BYTES,
  MAX_DELIVERY_RECORDS,
  type DeliveryReceipt,
  type HistoryExportBatch,
  type HistoryExportRecord,
} from "../src/lib/delivery-contracts.js";
import { splitSqlStatements } from "../src/migrate/split-sql-statements.js";
import { createDeliveryRoutes } from "../src/routes/delivery.js";
import { createTestDatabase, type TestDatabase } from "./support/database.js";
// The routes use the real migrated database, injected as the engine's database dependency.
const deliveryRoutes = createDeliveryRoutes({ database: () => database.db });
let database: TestDatabase;
let db: DeliveryDb;
const auth: AuthContext = {
  orgId: "org-fixture",
  workspaceId: "workspace-fixture",
  userId: "user-fixture",
  tokenSubject: "user-fixture",
  scopes: ["rth:sync", "rth:read"],
  claims: {},
};
function record(revision = 1, id = "record-1"): HistoryExportRecord {
  return {
    schema_version: 1,
    origin_id: "origin-fixture",
    record_id: id,
    revision_id: `${id}-revision-${revision}`,
    revision,
    kind: "history",
    source: "claude",
    session_id: "session-fixture",
    operation: "upsert",
    payload: {
      source: "claude",
      session_id: "session-fixture",
      prompt: `revision ${revision}`,
      timestamp_ms: 42,
    },
  };
}
function batch(records = [record()], id = "batch-1"): HistoryExportBatch {
  return {
    schema_version: 1,
    origin_id: "origin-fixture",
    batch_id: id,
    job_id: "job-fixture",
    generation: 1,
    destination_id: "relayhistory",
    instance_id: "fixture",
    account_id:
      "relayhistory:" +
      createHash("sha256")
        .update(JSON.stringify([auth.orgId, auth.workspaceId ?? ""]))
        .digest("hex"),
    mapping_version: "relayhistory-delivery-v1",
    records,
  };
}
function app(context = auth) {
  const result = new Hono<HistoryEnv>();
  result.use("*", async (c, next) => {
    c.set("auth", context);
    await next();
  });
  result.route("/v1", deliveryRoutes);
  return result;
}
function post(value: unknown, context = auth) {
  return app(context).request("/v1/delivery/batches", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(value),
  });
}
async function stored() {
  return (
    await database.query<Record<string, unknown>>(
      "SELECT *, revision::float8 AS revision FROM delivery_records ORDER BY record_id",
    )
  ).rows;
}

beforeAll(async () => {
  database = await createTestDatabase();
  db = database.db;
});
beforeEach(async () => {
  await database.exec(
    "TRUNCATE delivery_records, delivery_receipts, delivery_origins",
  );
});
afterAll(async () => {
  await database?.close();
});

describe("durable receipt protocol against migrated PostgreSQL", () => {
  it("accepts the real local SDK/native generated batch fixture", async () => {
    const wire: unknown = JSON.parse(
      await readFile(
        new URL("./fixtures/delivery-native-v1.json", import.meta.url),
        "utf8",
      ),
    );
    const parsed = parseDeliveryRequest(wire);
    // This fixture is generated by the local transcript exporter. The two
    // control-plane evidence kinds are covered below because they originate in
    // Cloud rather than the local exporter.
    expect(
      [...new Set(parsed.records.map((item) => item.kind))].sort(),
    ).toEqual(
      DELIVERY_KINDS.filter(
        (kind) => kind !== "session_lineage" && kind !== "turn_receipt",
      ).sort(),
    );
    const fixturePayload = (kind: HistoryExportRecord["kind"]) =>
      parsed.records.find((item) => item.kind === kind)!.payload as Record<
        string,
        unknown
      >;
    expect(fixturePayload("session_event")).toMatchObject({
      project_key: "AgentWorkforce/relayhistory",
      provider: "anthropic",
      request_span: "request-1:0",
      raw_facts_version: 2,
    });
    expect(fixturePayload("session")).toMatchObject({
      project_key: "AgentWorkforce/relayhistory",
      project_key_method: "git_remote",
    });
    expect(fixturePayload("relationship")).toMatchObject({
      origin_session_id: "remote-only",
    });
    expect(fixturePayload("session_marker")).toMatchObject({
      marker_uid: "fixture-marker",
      payload_json: JSON.stringify({ reason: "fixture" }),
    });
    const response = await post(wire);
    expect(response.status).toBe(200);
    expect(await response.json()).toMatchObject({
      acceptedRevisionIds: parsed.records.map((item) => item.revision_id),
    });
    const retained = (await listDelivery(db, auth, {})).records;
    expect(retained).toHaveLength(parsed.records.length);
    for (const item of parsed.records) {
      const kept = retained.find((row) => row.record_id === item.record_id)!
        .payload as Record<string, unknown>;
      const expected = Object.keys(item.payload!).filter(
        (key) => key !== "raw_path" && key !== "raw_locator",
      );
      expect(Object.keys(kept).sort()).toEqual(expected.sort());
    }
  });
  it("commits before responding and exactly replays a lost response without applying twice", async () => {
    const body = { protocolVersion: 1, batch: batch() };
    const first = await post(body);
    expect(first.status).toBe(200);
    const receipt = await first.json();
    expect(receipt).toEqual({
      protocolVersion: 1,
      receiptId: expect.stringMatching(/^rhr_[a-f0-9]{64}$/),
      batchId: "batch-1",
      acceptedRevisionIds: ["record-1-revision-1"],
      unsupportedRevisionIds: [],
      acceptanceLevel: "durable",
      limits: { maxRecords: 500, maxRequestBytes: 2_097_152 },
    });
    const second = await post(JSON.parse(canonicalJson(body)));
    expect(await second.json()).toEqual(receipt);
    expect(await stored()).toHaveLength(1);
    const receipts = (
      await database.query<{ receipt: Record<string, unknown> }>(
        "SELECT receipt FROM delivery_receipts",
      )
    ).rows;
    expect(receipts).toHaveLength(1);
    // Limits are response-time advice, never part of the stored, replayed receipt.
    const { limits: _limits, ...persisted } = receipt as Record<
      string,
      unknown
    >;
    expect(receipts[0].receipt).toEqual(persisted);
  });

  it("replays a stored receipt with the limits in force at replay time", async () => {
    const body = { protocolVersion: 1, batch: batch() };
    const receipt = await (await post(body)).json();
    const before = (
      await database.query("SELECT receipt FROM delivery_receipts")
    ).rows;
    // A receipt stored before `limits` shipped looks exactly like today's stored row.
    expect(before[0]).not.toHaveProperty("receipt.limits");
    const replay = await (await post(body)).json();
    expect(replay).toEqual(receipt);
    expect(
      (await database.query("SELECT receipt FROM delivery_receipts")).rows,
    ).toEqual(before);
  });

  it("publishes the batch limits to sync clients before their first batch", async () => {
    const response = await app().request("/v1/delivery/limits", {});
    expect(response.status).toBe(200);
    expect(await response.json()).toEqual({
      maxRecords: MAX_DELIVERY_RECORDS,
      maxRequestBytes: MAX_DELIVERY_BYTES,
    });
    const readOnly = await app({ ...auth, scopes: ["rth:read"] }).request(
      "/v1/delivery/limits",
      {},
    );
    expect(readOnly.status).toBe(403);
  });

  it("accepts a batch at the record limit in one durable receipt", async () => {
    const records = Array.from({ length: MAX_DELIVERY_RECORDS }, (_, index) =>
      record(1, `full-${String(index).padStart(4, "0")}`),
    );
    const response = await post({
      protocolVersion: 1,
      batch: batch(records, "batch-full"),
    });
    expect(response.status).toBe(200);
    const receipt = (await response.json()) as DeliveryReceipt;
    expect(receipt.acceptedRevisionIds).toEqual(
      records.map((item) => item.revision_id),
    );
    expect(await stored()).toHaveLength(MAX_DELIVERY_RECORDS);
  });

  it("adds the deterministic receipt id when replaying a pre-upgrade receipt", async () => {
    const body = { protocolVersion: 1, batch: batch() };
    const first = await post(body);
    const receipt = await first.json();
    await database.exec(
      "UPDATE delivery_receipts SET receipt = receipt - 'receiptId'",
    );
    const replay = await post(body);
    expect(await replay.json()).toEqual(receipt);
  });

  it("durably carries scrubbed lineage and existing-session turn receipts", async () => {
    const lineage = record(2, "lineage-1");
    lineage.kind = "session_lineage";
    lineage.session_id = "coding-session";
    lineage.payload = {
      id: "lineage-1",
      lineage_id: "lin_123",
      source_session_source: "codex",
      source_session_id: "source-session",
      source_transcript_id: "rht_source",
      source_prompt_ref: "prompt-1",
      source_prompt_digest: "b".repeat(64),
      issue_provider: "github",
      issue_ref: "acme/app#7",
      issue_source_ref: "relay-issue-event-7",
      issue_url: "https://github.com/acme/app/issues/7",
      garden_run_id: "run-123",
      coding_session_harness: "codex",
      coding_session_id: "coding-session",
      coding_transcript_id: "rht_sandbox",
      pr_provider: "github",
      pr_ref: "acme/app#8",
      pr_url: "https://github.com/acme/app/pull/8",
      created_at_ms: 1,
      updated_at_ms: 2,
      retention_class: "standard_30d",
      expires_at_ms: 42,
      raw: { token: "must-not-survive" },
      note: "undeclared prose is not a control-plane reference",
    };
    const turn = record(2, "turn-1");
    turn.kind = "turn_receipt";
    turn.session_id = "coding-session";
    turn.payload = {
      id: "turn-1",
      lineage_id: "lin_123",
      delivery_id: "del_123",
      status: "completed",
      head_sha: "a".repeat(40),
      sequence: 3,
      queued_at_ms: 1,
      delivered_at_ms: 2,
      completed_at_ms: 3,
      coding_session_harness: "codex",
      coding_session_id: "coding-session",
      transcript_id: "rht_sandbox",
      retention_class: "standard_30d",
      expires_at_ms: 42,
    };

    const response = await post({
      protocolVersion: 1,
      batch: batch([lineage, turn], "batch-lineage"),
    });
    expect(response.status).toBe(200);
    const receipt = await response.json();
    expect(receipt).toMatchObject({
      receiptId: expect.stringMatching(/^rhr_[a-f0-9]{64}$/),
      acceptanceLevel: "durable",
      acceptedRevisionIds: ["lineage-1-revision-2", "turn-1-revision-2"],
    });
    const rows = await stored();
    expect(rows[0].payload).toMatchObject({
      source_session_id: "source-session",
      source_prompt_ref: "prompt-1",
      source_prompt_digest: "b".repeat(64),
      issue_source_ref: "relay-issue-event-7",
      coding_session_id: "coding-session",
      garden_run_id: "run-123",
      pr_url: "https://github.com/acme/app/pull/8",
      retention_class: "standard_30d",
    });
    expect(rows[0].payload).not.toHaveProperty("raw");
    expect(rows[0].payload).not.toHaveProperty("note");
    expect(rows[1].payload).toMatchObject({
      delivery_id: "del_123",
      status: "completed",
      head_sha: "a".repeat(40),
      sequence: 3,
    });
    // No scheduled tick has run: an immediate read must still hide and clear
    // expired payloads without deleting their revision/digest fences.
    expect(
      (await listDelivery(db, auth, { kind: "session_lineage" })).records,
    ).toEqual([]);
    expect(await stored()).toEqual([
      expect.objectContaining({
        record_id: "lineage-1",
        revision: 2,
        operation: "delete",
        payload: null,
      }),
      expect.objectContaining({
        record_id: "turn-1",
        revision: 2,
        operation: "delete",
        payload: null,
      }),
    ]);

    // A delayed lower revision cannot resurrect data after retention expiry.
    const stale = { ...lineage, revision: 1, revision_id: "lineage-1-stale" };
    expect(
      (
        await post({
          protocolVersion: 1,
          batch: batch([stale], "batch-stale-lineage"),
        })
      ).status,
    ).toBe(200);
    expect((await stored())[0]).toMatchObject({
      revision: 2,
      operation: "delete",
      payload: null,
    });

    // Equal-revision identity reuse with changed transcript-like content still conflicts.
    const conflicting = structuredClone(lineage);
    conflicting.payload!.source_prompt_ref = "different-prompt";
    expect(
      (
        await post({
          protocolVersion: 1,
          batch: batch([conflicting], "batch-conflicting-lineage"),
        })
      ).status,
    ).toBe(409);
  });

  it("rejects transcript prose in control-plane reference fields", async () => {
    const lineage = record(1, "lineage-prose");
    lineage.kind = "session_lineage";
    lineage.session_id = "coding-session";
    lineage.payload = {
      id: "lineage-prose",
      lineage_id: "lin_123",
      source_session_source: "codex",
      source_session_id: "source-session",
      source_prompt_ref:
        "User: please paste the full transcript here\nAssistant: secret prose",
      source_prompt_digest: "b".repeat(64),
      coding_session_harness: "codex",
      coding_session_id: "coding-session",
      pr_provider: "github",
      pr_ref: "acme/app#8",
      pr_url: "https://github.com/acme/app/pull/8",
      created_at_ms: 1,
      updated_at_ms: 2,
      retention_class: "standard_30d",
      expires_at_ms: Date.now() + 60_000,
    };
    const response = await post({
      protocolVersion: 1,
      batch: batch([lineage], "batch-prose"),
    });
    expect(response.status).toBe(400);
    expect(await stored()).toEqual([]);

    lineage.payload!.source_prompt_ref = "prompt-1";
    lineage.payload!.issue_source_ref =
      "User: pasted issue-creation transcript\nAssistant: private prose";
    const issueSource = await post({
      protocolVersion: 1,
      batch: batch([lineage], "batch-issue-source-prose"),
    });
    expect(issueSource.status).toBe(400);
    expect(await stored()).toEqual([]);
  });

  it("accepts a claude origin-session lineage and its turn receipt", async () => {
    // The shape cloud writes for an origin-session bind: the claude session is
    // both source and coding session, with no Garden run or issue.
    const lineage = record(1, "lineage-claude");
    lineage.kind = "session_lineage";
    lineage.session_id = "claude-session";
    lineage.payload = {
      id: "lineage-claude",
      lineage_id: "lin_claude",
      source_session_source: "claude",
      source_session_id: "claude-session",
      source_transcript_id: null,
      source_prompt_ref: null,
      source_prompt_digest: "c".repeat(64),
      issue_provider: null,
      issue_ref: null,
      issue_source_ref: null,
      issue_url: null,
      garden_run_id: null,
      coding_session_harness: "claude",
      coding_session_id: "claude-session",
      coding_transcript_id: null,
      pr_provider: "github",
      pr_ref: "acme/app#9",
      pr_url: "https://github.com/acme/app/pull/9",
      created_at_ms: 1,
      updated_at_ms: 2,
      retention_class: "standard_30d",
      expires_at_ms: Date.now() + 60_000,
    };
    const turn = record(1, "turn-claude");
    turn.kind = "turn_receipt";
    turn.session_id = "claude-session";
    turn.payload = {
      id: "turn-claude",
      lineage_id: "lin_claude",
      delivery_id: "del_claude",
      status: "queued",
      head_sha: "d".repeat(40),
      sequence: 1,
      queued_at_ms: 1,
      delivered_at_ms: 0,
      completed_at_ms: 0,
      coding_session_harness: "claude",
      coding_session_id: "claude-session",
      transcript_id: null,
      retention_class: "standard_30d",
      expires_at_ms: Date.now() + 60_000,
    };
    const response = await post({
      protocolVersion: 1,
      batch: batch([lineage, turn], "batch-claude-lineage"),
    });
    expect(response.status).toBe(200);
    const rows = await stored();
    expect(rows.map((row) => row.payload)).toEqual([
      expect.objectContaining({ coding_session_harness: "claude" }),
      expect.objectContaining({ coding_session_harness: "claude" }),
    ]);
  });

  it("still rejects a missing or prose coding_session_harness", async () => {
    for (const [index, harness] of [
      undefined,
      null,
      "",
      "Claude Code",
      "claude\nprose",
      // JavaScript `$` (no `m` flag) is end-of-input, so a trailing line
      // terminator can never satisfy CONTROL_PLANE_KIND.
      "claude\n",
      "claude\r\n",
      "claude\r",
      "claude\u2028",
      "x".repeat(33),
    ].entries()) {
      const turn = record(1, "turn-bad-harness");
      turn.kind = "turn_receipt";
      turn.session_id = "coding-session";
      turn.payload = {
        id: "turn-bad-harness",
        lineage_id: "lin_123",
        delivery_id: "del_123",
        status: "queued",
        head_sha: "a".repeat(40),
        sequence: 1,
        queued_at_ms: 1,
        delivered_at_ms: 0,
        completed_at_ms: 0,
        coding_session_harness: harness,
        coding_session_id: "coding-session",
        retention_class: "standard_30d",
        expires_at_ms: Date.now() + 60_000,
      };
      const response = await post({
        protocolVersion: 1,
        batch: batch([turn], `batch-bad-harness-${index}`),
      });
      expect(response.status, JSON.stringify(harness)).toBe(400);
    }
    for (const [index, harness] of ["claude\n", "claude\r\n"].entries()) {
      const lineage = record(1, "lineage-bad-harness");
      lineage.kind = "session_lineage";
      lineage.session_id = "claude-session";
      lineage.payload = {
        id: "lineage-bad-harness",
        lineage_id: "lin_bad",
        source_session_source: "claude",
        source_session_id: "claude-session",
        source_prompt_digest: "c".repeat(64),
        coding_session_harness: harness,
        coding_session_id: "claude-session",
        pr_provider: "github",
        pr_ref: "acme/app#9",
        pr_url: "https://github.com/acme/app/pull/9",
        created_at_ms: 1,
        updated_at_ms: 2,
        retention_class: "standard_30d",
        expires_at_ms: Date.now() + 60_000,
      };
      const response = await post({
        protocolVersion: 1,
        batch: batch([lineage], `batch-bad-lineage-harness-${index}`),
      });
      expect(response.status, JSON.stringify(harness)).toBe(400);
    }
    expect(await stored()).toEqual([]);
  });

  it("rejects contradictory GitHub references and endpoint kinds", async () => {
    const lineage = record(1, "lineage-mismatch");
    lineage.kind = "session_lineage";
    lineage.session_id = "coding-session";
    lineage.payload = {
      id: "lineage-mismatch",
      lineage_id: "lin_123",
      source_session_source: "codex",
      source_session_id: "source-session",
      issue_provider: "github",
      issue_ref: "acme/app#7",
      issue_url: "https://github.com/acme/app/issues/7",
      coding_session_harness: "codex",
      coding_session_id: "coding-session",
      pr_provider: "github",
      pr_ref: "acme/app#8",
      pr_url: "https://github.com/acme/other/pull/8",
      created_at_ms: 1,
      updated_at_ms: 2,
      retention_class: "standard_30d",
      expires_at_ms: Date.now() + 60_000,
    };
    const response = await post({
      protocolVersion: 1,
      batch: batch([lineage], "batch-mismatch"),
    });
    expect(response.status).toBe(400);
    expect(await stored()).toEqual([]);
    lineage.payload!.pr_url = "https://github.com/acme/app/pull/8";
    lineage.payload!.issue_url = "https://github.com/acme/app/pull/7";
    const wrongEndpoint = await post({
      protocolVersion: 1,
      batch: batch([lineage], "batch-wrong-endpoint"),
    });
    expect(wrongEndpoint.status).toBe(400);
    expect(await stored()).toEqual([]);
  });

  it("expires inactive-tenant payloads through the scheduled global sweep", async () => {
    const turn = record(1, "turn-scheduled-expiry");
    turn.kind = "turn_receipt";
    turn.session_id = "coding-session";
    turn.payload = {
      id: "turn-scheduled-expiry",
      lineage_id: "lin_123",
      delivery_id: "bst_123",
      status: "delivered",
      head_sha: "a".repeat(40),
      sequence: 2,
      queued_at_ms: 1,
      delivered_at_ms: 2,
      completed_at_ms: 0,
      coding_session_harness: "codex",
      coding_session_id: "coding-session",
      transcript_id: "rht_sandbox",
      retention_class: "standard_30d",
      expires_at_ms: 42,
    };
    expect(
      (
        await post({
          protocolVersion: 1,
          batch: batch([turn], "batch-scheduled-expiry"),
        })
      ).status,
    ).toBe(200);
    expect(await expireBabysitterEvidence(db)).toBe(1);
    expect((await stored())[0]).toMatchObject({
      record_id: "turn-scheduled-expiry",
      revision: 1,
      operation: "delete",
      payload: null,
    });
  });
  it("rejects batch identity reuse even when transformed content is unchanged", async () => {
    const value = batch();
    await acceptDelivery(db, auth, value);
    const currentDigest = await digest({ protocolVersion: 1, batch: value });
    value.records[0].payload!.raw = "different excluded blob";
    const submittedDigest = await digest({ protocolVersion: 1, batch: value });
    const response = await post({ protocolVersion: 1, batch: value });
    expect(response.status).toBe(409);
    expect(await response.json()).toEqual({
      error: {
        code: "delivery_conflict",
        message: "Delivery batch identity was reused with different content",
        conflict: {
          type: "batch_id",
          originId: value.origin_id,
          batchId: value.batch_id,
          submittedDigest,
          currentDigest,
        },
      },
      correlationId: "",
    });
    expect((await stored())[0].revision).toBe(1);
  });
  it("returns every current revision conflict and atomically writes no prefix", async () => {
    const currentY = record(2, "y");
    const currentZ = record(2, "z");
    await acceptDelivery(db, auth, batch([currentZ, currentY]));
    const conflictingY = structuredClone(currentY);
    conflictingY.payload!.prompt = "conflicting y";
    const conflictingZ = structuredClone(currentZ);
    conflictingZ.payload!.prompt = "conflicting z";
    const submitted = batch(
      [record(1, "a"), conflictingZ, conflictingY],
      "batch-conflict",
    );
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    try {
      const response = await post({ protocolVersion: 1, batch: submitted });
      expect(response.status).toBe(409);
      const yConflict = {
        type: "record_revision",
        originId: submitted.origin_id,
        recordId: "y",
        submittedRevisionId: conflictingY.revision_id,
        submittedRevision: conflictingY.revision,
        submittedDigest: await digest(conflictingY),
        currentRevisionId: currentY.revision_id,
        currentRevision: currentY.revision,
        currentDigest: await digest(currentY),
      };
      const zConflict = {
        type: "record_revision",
        originId: submitted.origin_id,
        recordId: "z",
        submittedRevisionId: conflictingZ.revision_id,
        submittedRevision: conflictingZ.revision,
        submittedDigest: await digest(conflictingZ),
        currentRevisionId: currentZ.revision_id,
        currentRevision: currentZ.revision,
        currentDigest: await digest(currentZ),
      };
      expect(await response.json()).toEqual({
        error: {
          code: "delivery_conflict",
          message: "Delivery record revision was reused with different content",
          conflict: yConflict,
          conflicts: [yConflict, zConflict],
          conflictCount: 2,
        },
        correlationId: "",
      });
      expect(warn).toHaveBeenCalledTimes(1);
      const line = String(warn.mock.calls[0][0]);
      expect(JSON.parse(line)).toMatchObject({
        event: "delivery.conflict",
        orgId: auth.orgId,
        workspaceId: auth.workspaceId,
        originId: submitted.origin_id,
        batchId: submitted.batch_id,
        type: "record_revision",
        conflictCount: 2,
        conflicts: [
          {
            recordId: "y",
            submittedRevisionId: conflictingY.revision_id,
            currentRevisionId: currentY.revision_id,
          },
          {
            recordId: "z",
            submittedRevisionId: conflictingZ.revision_id,
            currentRevisionId: currentZ.revision_id,
          },
        ],
      });
      expect(line).not.toContain("conflicting y");
      expect(line).not.toContain(await digest(conflictingY));
    } finally {
      warn.mockRestore();
    }
    expect((await stored()).map((row) => row.record_id)).toEqual(["y", "z"]);
    expect(
      (await database.query("SELECT * FROM delivery_receipts")).rows,
    ).toHaveLength(1);
  });
  it("rejects equal revision reuse within one batch and names the submitted peer", async () => {
    const current = record(1, "n");
    const twin = structuredClone(current);
    twin.revision_id = "n-revision-1-twin";
    twin.payload!.prompt = "conflicting twin";
    const submitted = batch([twin, current], "batch-twin-revision");
    const response = await post({ protocolVersion: 1, batch: submitted });
    expect(response.status).toBe(409);
    const conflict = {
      type: "record_revision",
      originId: submitted.origin_id,
      recordId: twin.record_id,
      submittedRevisionId: twin.revision_id,
      submittedRevision: twin.revision,
      submittedDigest: await digest(twin),
      currentRevisionId: current.revision_id,
      currentRevision: current.revision,
      currentDigest: await digest(current),
    };
    expect(await response.json()).toEqual({
      error: {
        code: "delivery_conflict",
        message: "Delivery record revision was reused with different content",
        conflict,
        conflicts: [conflict],
        conflictCount: 1,
      },
      correlationId: "",
    });
    expect(await stored()).toEqual([]);
    expect(
      (await database.query("SELECT * FROM delivery_receipts")).rows,
    ).toHaveLength(0);
    expect(
      (await database.query("SELECT * FROM delivery_origins")).rows,
    ).toHaveLength(0);
  });
  it("caps named record conflicts and reports the total", async () => {
    const ids = Array.from({ length: 101 }, (_, index) => `cap-${index}`);
    const current = ids.map((id) => record(1, id));
    await acceptDelivery(db, auth, batch(current));
    const changed = current.map((item) => {
      const copy = structuredClone(item);
      copy.payload!.prompt = "conflicting";
      return copy;
    });
    const response = await post({
      protocolVersion: 1,
      batch: batch(changed, "batch-capped-conflicts"),
    });
    expect(response.status).toBe(409);
    const { error } = (await response.json()) as {
      error: {
        conflict: { recordId: string };
        conflicts: { recordId: string }[];
        conflictCount: number;
      };
    };
    expect(error.conflictCount).toBe(101);
    expect(error.conflicts).toHaveLength(100);
    expect(error.conflict).toEqual(error.conflicts[0]);
    expect(await stored()).toHaveLength(101);
  });
  it("keeps a typed 409 when PostgreSQL and UTF-16 order Unicode differently", async () => {
    const ids = ["\uE000", "\u{10000}"];
    const current = ids.map((id) => record(1, id));
    await acceptDelivery(db, auth, batch(current));
    const changed = current.map((item) => {
      const copy = structuredClone(item);
      copy.payload!.prompt = "conflicting";
      return copy;
    });
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    try {
      const response = await post({
        protocolVersion: 1,
        batch: batch(changed, "batch-unicode-order"),
      });
      expect(response.status).toBe(409);
      const { error } = (await response.json()) as {
        error: {
          conflict: unknown;
          conflicts: { recordId: string }[];
          conflictCount: number;
        };
      };
      expect(error.conflictCount).toBe(2);
      expect(error.conflict).toEqual(error.conflicts[0]);
      expect(new Set(error.conflicts.map((item) => item.recordId))).toEqual(
        new Set(ids),
      );
    } finally {
      warn.mockRestore();
    }
  });
  it("keeps opaque 0009 conflicts compatible and logs their scope", async () => {
    const functionStatements = async (name: string) =>
      splitSqlStatements(
        await readFile(
          new URL(`../migrations/${name}`, import.meta.url),
          "utf8",
        ),
      ).filter((statement: string) =>
        statement.includes("FUNCTION sessions.accept_delivery_batch"),
      );
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    try {
      for (const statement of await functionStatements(
        "0009_durable_delivery.sql",
      ))
        await database.exec(statement);
      const current = record(2, "legacy");
      await acceptDelivery(db, auth, batch([current]));
      const changed = structuredClone(current);
      changed.payload!.prompt = "conflicting";
      const response = await post({
        protocolVersion: 1,
        batch: batch([changed], "batch-old-function"),
      });
      expect(response.status).toBe(409);
      expect(await response.json()).toEqual({
        error: {
          code: "delivery_conflict",
          message: "Delivery identity was reused with different content",
        },
        correlationId: "",
      });
      expect(warn).toHaveBeenCalledTimes(1);
      expect(JSON.parse(String(warn.mock.calls[0][0]))).toMatchObject({
        event: "delivery.conflict",
        originId: "origin-fixture",
        batchId: "batch-old-function",
        type: "unknown",
      });
    } finally {
      warn.mockRestore();
      for (const statement of await functionStatements(
        "0026_typed_delivery_conflicts.sql",
      ))
        await database.exec(statement);
    }
  });
  it("serializes overlapping concurrent requests and never overwrites a newer revision", async () => {
    const responses = await Promise.all(
      [3, 1, 2, 5, 4].map((n) =>
        post({ protocolVersion: 1, batch: batch([record(n)], `batch-${n}`) }),
      ),
    );
    expect(responses.map((response) => response.status)).toEqual([
      200, 200, 200, 200, 200,
    ]);
    expect((await stored())[0]).toMatchObject({
      revision: 5,
      payload: { prompt: "revision 5" },
    });
    const stale = await post({
      protocolVersion: 1,
      batch: batch([record(1)], "batch-stale"),
    });
    expect(await stale.json()).toMatchObject({
      acceptedRevisionIds: ["record-1-revision-1"],
    });
    expect((await stored())[0].revision).toBe(5);
  });
  it("accepts equal semantic revisions in another batch and concurrent identical receipts", async () => {
    const results = await Promise.all([
      post({ protocolVersion: 1, batch: batch() }),
      post({ protocolVersion: 1, batch: batch() }),
    ]);
    expect(results.map((response) => response.status)).toEqual([200, 200]);
    expect(
      (await post({ protocolVersion: 1, batch: batch([record()], "second") }))
        .status,
    ).toBe(200);
    expect(await stored()).toHaveLength(1);
  });
  it("accepts multiple revisions of one record in mixed order with exact outcomes", async () => {
    const deleted = {
      ...record(3),
      operation: "delete" as const,
      payload: null,
    };
    const value = batch([deleted, record(1), record(2)]);
    const result = await post({ protocolVersion: 1, batch: value });
    expect(result.status).toBe(200);
    expect(await result.json()).toMatchObject({
      acceptedRevisionIds: value.records.map((item) => item.revision_id),
    });
    expect((await stored())[0]).toMatchObject({
      revision: 3,
      operation: "delete",
      payload: null,
    });
  });
  it("keeps tombstone fence, clears plaintext, and prevents stale resurrection", async () => {
    await acceptDelivery(db, auth, batch());
    const deleted = {
      ...record(2),
      operation: "delete" as const,
      payload: null,
    };
    await acceptDelivery(db, auth, batch([deleted], "delete"));
    await acceptDelivery(db, auth, batch([record()], "late"));
    expect((await stored())[0]).toMatchObject({
      revision: 2,
      operation: "delete",
      payload: null,
    });
    expect((await listDelivery(db, auth, {})).records).toEqual([]);
    expect(
      (await listDelivery(db, auth, { include_deleted: "true" })).records,
    ).toHaveLength(1);
    expect(
      JSON.stringify(
        (await database.query("SELECT receipt FROM delivery_receipts")).rows,
      ),
    ).not.toContain("revision 1");
  });
  it("rolls back actual database failure midway through batch, then permits safe retry", async () => {
    await database.exec(
      `CREATE FUNCTION delivery_test_fault() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.record_id='z' THEN RAISE EXCEPTION 'injected failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER delivery_fault BEFORE INSERT ON delivery_records FOR EACH ROW EXECUTE FUNCTION delivery_test_fault()`,
    );
    const value = {
      protocolVersion: 1,
      batch: batch([record(1, "a"), record(1, "z")]),
    };
    try {
      const failed = await post(value);
      expect(failed.status).toBe(503);
      expect(await failed.text()).not.toContain("injected");
      expect(await stored()).toHaveLength(0);
      expect(
        (await database.query("SELECT * FROM delivery_receipts")).rows,
      ).toHaveLength(0);
    } finally {
      await database.exec(
        "DROP TRIGGER delivery_fault ON delivery_records; DROP FUNCTION delivery_test_fault()",
      );
    }
    expect((await post(value)).status).toBe(200);
    expect(await stored()).toHaveLength(2);
  });
  it("rejects swapped bearer tenancy on delivery and readback before any writes", async () => {
    const other = { ...auth, workspaceId: "swapped-workspace" };
    const response = await post({ protocolVersion: 1, batch: batch() }, other);
    expect(response.status).toBe(403);
    expect(await response.json()).toMatchObject({
      error: { code: "delivery_account_mismatch" },
    });
    expect(await stored()).toHaveLength(0);
    expect(
      (await database.query("SELECT * FROM delivery_receipts")).rows,
    ).toHaveLength(0);
    const read = await app(other).request("/v1/delivery/records", {
      headers: {
        "X-RelayHistory-Expected-Account": await deliveryAccount(auth),
      },
    });
    expect(read.status).toBe(403);
    expect((await app().request("/v1/delivery/records", {})).status).toBe(403);
  });
  it("isolates org/workspace tenancy, ignoring client account labels", async () => {
    await acceptDelivery(db, auth, batch());
    const other = { ...auth, orgId: "other-org" };
    const workspace = { ...auth, workspaceId: "other-workspace" };
    expect((await listDelivery(db, other, {})).records).toHaveLength(0);
    expect((await listDelivery(db, workspace, {})).records).toHaveLength(0);
    const changed = batch();
    changed.records[0].payload!.prompt = "other";
    changed.account_id = await deliveryAccount(other);
    await acceptDelivery(db, other, changed);
    changed.account_id = await deliveryAccount(workspace);
    await acceptDelivery(db, workspace, changed);
    expect(await stored()).toHaveLength(3);
    expect((await listDelivery(db, auth, {})).records[0].payload).toMatchObject(
      { prompt: "revision 1" },
    );
  });
  it("uses deterministic live pagination bound to scope/filters, including Unicode identities", async () => {
    const records = ["a", "b", "c", "é"].map((id) => record(1, id));
    records[2].source = "codex";
    records[2].session_id = "other";
    await acceptDelivery(db, auth, batch(records));
    const first = await listDelivery(db, auth, {
      limit: "1",
      source: "claude",
      session_id: "session-fixture",
    });
    expect(first.listing).toBe("live");
    expect(first.records[0].record_id).toBe("a");
    const second = await listDelivery(db, auth, {
      limit: "1",
      source: "claude",
      session_id: "session-fixture",
      cursor: first.nextCursor!,
    });
    expect(second.records[0].record_id).toBe("b");
    const last = await listDelivery(db, auth, {
      limit: "1",
      source: "claude",
      session_id: "session-fixture",
      cursor: second.nextCursor!,
    });
    expect(last.records[0].record_id).toBe("é");
    expect(last.nextCursor).toBeNull();
    await expect(
      listDelivery(db, auth, { cursor: first.nextCursor! }),
    ).rejects.toMatchObject({ status: 400 });
    await expect(
      listDelivery(
        db,
        { ...auth, workspaceId: "other" },
        {
          source: "claude",
          session_id: "session-fixture",
          cursor: first.nextCursor!,
        },
      ),
    ).rejects.toMatchObject({ status: 400 });
    const response = await app().request(
      "/v1/delivery/records?kind=history&source=codex",
      {
        headers: {
          "X-RelayHistory-Expected-Account": await deliveryAccount(auth),
        },
      },
    );
    expect(await response.json()).toMatchObject({
      records: [{ record_id: "c" }],
    });
  });
  it("scrubs readable and structured canonical evidence while dropping whole provider raw blobs", async () => {
    const tool = {
      ...record(1, "tool"),
      kind: "tool_call" as const,
      payload: {
        name: "shell",
        args_json: JSON.stringify({
          path: "/Users/synthetic/project",
          command: "Bearer synthetic_secret",
          raw: { environment: "do not retain" },
        }),
        raw: "provider blob",
      },
    };
    const edit = {
      ...record(1, "edit"),
      kind: "file_edit" as const,
      payload: {
        file_path: "/Users/synthetic/project/a.ts",
        lines_added: 1,
        structured_patch_json: JSON.stringify([
          { old: "alice@example.com", new: "safe" },
        ]),
      },
    };
    await acceptDelivery(db, auth, batch([tool, edit]));
    const values = (await listDelivery(db, auth, {})).records;
    expect(values[0].payload).toMatchObject({
      file_path: "~/project/a.ts",
      lines_added: 1,
    });
    const patch = JSON.parse(
      (values[0].payload as Record<string, string>).structured_patch_json,
    );
    expect(patch[0].old).not.toContain("alice@example.com");
    const args = JSON.parse(
      (values[1].payload as Record<string, string>).args_json,
    );
    expect(args.path).toBe("~/project");
    expect(args.command).not.toContain("synthetic_secret");
    expect(args.raw).toBeUndefined();
    expect(JSON.stringify(values)).not.toContain("provider blob");
  });
  it("retains independent connector provenance and normalized observation evidence", async () => {
    const values: HistoryExportRecord[] = [
      "claude-web",
      "other-provider",
    ].flatMap((connector, index) => [
      {
        ...record(1, `observation-${index}`),
        kind: "source_observation",
        payload: {
          source: "claude",
          session_id: "session-fixture",
          location: "remote",
          connector_id: connector,
          connector_instance: "fixture",
          raw_locator: "provider raw location",
          source_stamp: "version-1",
          discovery_state: "full",
          access_state: "available",
          updated_ms: 42,
        },
      },
      {
        ...record(1, `evidence-${index}`),
        kind: "observation_evidence",
        payload: {
          source: "claude",
          session_id: "session-fixture",
          location: "remote",
          connector_id: connector,
          connector_instance: "fixture",
          evidence_uid: "event-1",
          payload_json: JSON.stringify({
            event: { role: "assistant", text: "synthetic evidence" },
          }),
        },
      },
    ]);
    await acceptDelivery(db, auth, batch(values));
    const observations = await listDelivery(db, auth, {
      kind: "source_observation",
    });
    expect(observations.records).toHaveLength(2);
    expect(
      observations.records.map(
        (row) => (row.payload as Record<string, unknown>).connector_id,
      ),
    ).toEqual(["claude-web", "other-provider"]);
    expect(JSON.stringify(observations)).not.toContain("provider raw location");
    const evidence = await listDelivery(db, auth, {
      kind: "observation_evidence",
    });
    expect(
      JSON.parse(
        (evidence.records[0].payload as Record<string, string>).payload_json,
      ),
    ).toEqual({ event: { role: "assistant", text: "synthetic evidence" } });
  });

  it("retains current event, session, relationship and marker evidence", async () => {
    const event = {
      ...record(1, "event"),
      kind: "session_event" as const,
      payload: {
        source: "claude",
        session_id: "session-fixture",
        project_key: "AgentWorkforce/relayhistory",
        project_key_method: "git_remote",
        provider: "anthropic",
        tool_use_id: "tool-use-1",
        payload_bytes: 2048,
        payload_truncated: false,
        payload_hash: "payload-hash",
        call_index: 2,
        event_index: 3,
        result_status: "completed",
        event_source: "provider",
        error_signal: "none",
        subagent_session_id: "child-session",
        agent_id: "agent-1",
        request_id: "request-1",
        provider_message_id: "message-1",
        stop_reason: "end_turn",
        agent_version: "1.2.3",
        is_sidechain: false,
        is_meta: true,
        turn_id: "turn-1",
        request_span: "request-1:0",
        raw_facts_version: 2,
        raw_kind: "assistant",
      },
    };
    const session = {
      ...record(1, "session"),
      kind: "session" as const,
      payload: {
        source: "claude",
        session_id: "session-fixture",
        project_key: "AgentWorkforce/relayhistory",
        project_key_method: "git_remote",
      },
    };
    const relationship = {
      ...record(1, "relationship"),
      kind: "relationship" as const,
      payload: {
        source: "claude",
        parent_session_id: "session-fixture",
        relationship_uid: "relationship-1",
        origin_session_id: "origin-session",
      },
    };
    const marker = {
      ...record(1, "marker"),
      kind: "session_marker" as const,
      payload: {
        source: "claude",
        session_id: "session-fixture",
        marker_uid: "marker-1",
        ts_ms: 42,
        message_id: "message-1",
        parent_id: "parent-1",
        turn_id: "turn-1",
        kind: "compaction_boundary",
        subkind: "summary",
        text: "alice@example.com",
        payload_json: JSON.stringify({
          reason: "Bearer synthetic_secret",
          raw: { transcript: "must not survive" },
        }),
      },
    };

    await acceptDelivery(
      db,
      auth,
      batch([event, session, relationship, marker]),
    );
    const values = (await listDelivery(db, auth, {})).records;
    const payload = (id: string) =>
      values.find((value) => value.record_id === id)!.payload as Record<
        string,
        unknown
      >;

    expect(payload("event")).toMatchObject(event.payload);
    expect(payload("session")).toMatchObject(session.payload);
    expect(payload("relationship")).toMatchObject(relationship.payload);
    expect(payload("marker")).toMatchObject({
      marker_uid: "marker-1",
      kind: "compaction_boundary",
      subkind: "summary",
    });
    expect(payload("marker").text).not.toBe("alice@example.com");
    expect(JSON.parse(payload("marker").payload_json as string)).toMatchObject({
      reason: expect.not.stringContaining("synthetic_secret"),
    });
    expect(JSON.stringify(payload("marker"))).not.toContain("must not survive");
  });

  it("stores every column of a real-shaped session and session_event row", async () => {
    const session = {
      ...record(3, "session-full"),
      kind: "session" as const,
      payload: {
        session_id: "session-fixture",
        source: "claude",
        cwd: "/Users/synthetic/project",
        git_branch: "main",
        first_activity_ms: 1_700_000_000_000,
        last_activity_ms: 1_700_000_360_000,
        last_assistant_text: "Done.",
        raw_path: "/Users/synthetic/.claude/projects/-project/session.jsonl",
        parser_version: 7,
        first_prompt: "Fix the build",
        models_json: JSON.stringify(["claude-opus", "claude-haiku"]),
        originator: "cli",
        agent_version: "2.1.0",
        repo_url: "https://github.com/acme/app",
        initial_commit: "a".repeat(40),
        workspace_roots_json: JSON.stringify(["/Users/synthetic/project"]),
        source_stamp: "stamp-1",
        discovery_state: "full",
        project_key: "acme/app",
        project_key_method: "git_remote",
      },
    };
    const eventPayload = {
      id: 17,
      source: "claude",
      session_id: "session-fixture",
      project: "app",
      project_key: "acme/app",
      project_key_method: "git_remote",
      cwd: "/workspace/app",
      git_branch: "main",
      message_id: "message-1",
      parent_id: "message-0",
      ts_ms: 1_700_000_100_000,
      role: "assistant",
      kind: "text",
      text: "Build is green.",
      model: "claude-opus",
      provider: "anthropic",
      event_uid: "event-uid-1",
      tool_use_id: null,
      payload_bytes: 512,
      payload_truncated: 0,
      payload_hash: "b".repeat(64),
      call_index: 0,
      event_index: 4,
      result_status: "ok",
      event_source: "transcript",
      error_signal: null,
      subagent_session_id: null,
      agent_id: "agent-1",
      request_id: "request-1",
      provider_message_id: "msg_1",
      stop_reason: "end_turn",
      agent_version: "2.1.0",
      is_sidechain: 0,
      is_meta: 0,
      turn_id: "turn-1",
      request_span: "request-1:0",
      raw_facts_version: 3,
      raw_kind: "assistant",
      token_json: JSON.stringify({ output: 12, input: 40 }),
      line_no: 88,
      content_hash: "c".repeat(64),
      thinking_tokens: 5,
    };
    const event = {
      ...record(3, "event-full"),
      kind: "session_event" as const,
      payload: eventPayload,
    };

    await acceptDelivery(db, auth, batch([session, event]));
    const values = (await listDelivery(db, auth, {})).records;
    const payload = (id: string) =>
      values.find((value) => value.record_id === id)!.payload;

    const { raw_path: _locator, ...retainedSession } = session.payload;
    expect(payload("session-full")).toEqual({
      ...retainedSession,
      cwd: "~/project",
      models_json: canonicalJson(["claude-opus", "claude-haiku"]),
      workspace_roots_json: canonicalJson(["~/project"]),
    });
    expect(payload("event-full")).toEqual({
      ...eventPayload,
      token_json: canonicalJson({ input: 40, output: 12 }),
    });
  });
  it("round-trips an unknown local column through acceptance and readback", async () => {
    const history = record(1, "history-extra");
    history.payload = {
      ...history.payload,
      id: 9,
      project: "app",
      prompt_hash: "d".repeat(64),
      git_branch: null,
      future_column: "alice@example.com wrote this",
      future_flag: 1,
      future_ratio: 0.25,
      future_nullable: null,
      future_meta_json: JSON.stringify({
        z: 1,
        a: "Bearer synthetic_secret_value_123",
      }),
    };
    expect(
      (await post({ protocolVersion: 1, batch: batch([history]) })).status,
    ).toBe(200);
    const response = await app().request("/v1/delivery/records?kind=history", {
      headers: {
        "X-RelayHistory-Expected-Account": await deliveryAccount(auth),
      },
    });
    expect(response.status).toBe(200);
    const {
      records: [read],
    } = (await response.json()) as {
      records: { payload: Record<string, unknown> }[];
    };
    expect(read.payload).toEqual({
      source: "claude",
      session_id: "session-fixture",
      prompt: "revision 1",
      timestamp_ms: 42,
      id: 9,
      project: "app",
      prompt_hash: "d".repeat(64),
      git_branch: null,
      future_column: "[REDACTED] wrote this",
      future_flag: 1,
      future_ratio: 0.25,
      future_nullable: null,
      future_meta_json: canonicalJson({ a: "Bearer [REDACTED]", z: 1 }),
    });
    expect((await stored())[0].payload).toEqual(read.payload);
  });
  it.each([
    ["a nested object value", { future_column: { nested: true } }],
    ["an array value", { future_column: [1, 2] }],
    ["a free-text field name", { "prompt text": "x" }],
    ["invalid models_json", { models_json: "not JSON" }],
    ["non-string workspace_roots_json", { workspace_roots_json: ["/a"] }],
    ["invalid JSON in an unknown *_json column", { future_json: "{" }],
  ])("rejects %s without writing the batch", async (_name, extra) => {
    const bad = {
      ...record(1, "bad-session"),
      kind: "session" as const,
      payload: { source: "claude", session_id: "session-fixture", ...extra },
    };
    const response = await post({
      protocolVersion: 1,
      batch: batch([record(), bad]),
    });
    expect(response.status).toBe(400);
    expect(await response.json()).toMatchObject({
      error: { code: "invalid_delivery" },
    });
    expect(await stored()).toHaveLength(0);
  });
  it("rejects malformed structured evidence without partially writing valid records", async () => {
    const malformed = {
      ...record(1, "bad"),
      kind: "tool_call" as const,
      payload: { args_json: "not JSON" },
    };
    expect(
      (await post({ protocolVersion: 1, batch: batch([record(), malformed]) }))
        .status,
    ).toBe(400);
    expect(await stored()).toHaveLength(0);
  });
  // PostgreSQL refuses to convert a lone surrogate to jsonb. Reported as 503 these are
  // retried forever, because no retry of the same bytes can ever be accepted. JSON
  // carries them as \ud800 escapes, so the bounded UTF-8 decode never sees one.
  it.each([
    [
      "a retained payload string",
      batch([
        { ...record(), payload: { ...record().payload, prompt: "\ud800" } },
      ]),
    ],
    ["an identifier", batch([{ ...record(), record_id: "record-\ud800" }])],
  ])(
    "rejects unpaired surrogates in %s as permanently invalid",
    async (_name, value) => {
      const response = await post({ protocolVersion: 1, batch: value });
      expect(response.status).toBe(400);
      expect(await response.json()).toMatchObject({
        error: { code: "invalid_delivery" },
      });
      expect(await stored()).toHaveLength(0);
    },
  );
  it("delivers a well-formed prompt whose surrogate pair straddles the scrub cut", async () => {
    // boundForScrub rewinds from MAX_SCRUB_CHARS hunting for whitespace and gives up
    // after SCRUB_CUT_REWIND characters, so with no whitespace in that window it cuts at
    // the floor. A pair sitting exactly there is the one the client never gets to fix:
    // the input is well formed and only the server's own cut could sever it. The floor
    // is internal to scrub.ts, so the premise is asserted rather than assumed — if the
    // cut moves, this fails here instead of quietly stopping exercising the boundary.
    const floor = MAX_SCRUB_CHARS - 62_144;
    const prompt =
      "a".repeat(floor - 1) + "\u{1F600}" + "a".repeat(MAX_SCRUB_CHARS);
    expect(scrubText(prompt)).toContain("[relayhistory: truncated");
    expect(
      servicePayload({ ...record(), payload: { ...record().payload, prompt } }),
    ).toMatchObject({ prompt: expect.stringContaining("[relayhistory:") });
    const response = await post({
      protocolVersion: 1,
      batch: batch([{ ...record(), payload: { ...record().payload, prompt } }]),
    });
    expect(response.status).toBe(200);
    expect(String((await stored())[0].payload)).not.toMatch(
      /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/,
    );
  });
  it("still rejects a surrogate already unpaired at that same cut", async () => {
    // The cut steps back only off a real pair. A high surrogate the client sent unpaired
    // has to survive the cut and be rejected here exactly as it would anywhere else —
    // otherwise this one offset would be the only place malformed input got through.
    const floor = MAX_SCRUB_CHARS - 62_144;
    const prompt =
      "a".repeat(floor - 1) + "\ud800" + "a".repeat(MAX_SCRUB_CHARS);
    expect(scrubText(prompt)).toMatch(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])/);
    const response = await post({
      protocolVersion: 1,
      batch: batch([{ ...record(), payload: { ...record().payload, prompt } }]),
    });
    expect(response.status).toBe(400);
    expect(await response.json()).toMatchObject({
      error: { code: "invalid_delivery" },
    });
    expect(await stored()).toHaveLength(0);
  });
  it.each([
    { protocolVersion: 2, batch: batch() },
    { protocolVersion: 1, batch: { ...batch(), schema_version: 2 } },
    {
      protocolVersion: 1,
      batch: batch([{ ...record(), kind: "unknown" as never }]),
    },
  ])("explicitly rejects unsupported protocol/schema/kind", async (value) => {
    expect((await post(value)).status).toBe(422);
    expect(await stored()).toHaveLength(0);
  });
  it("rejects unknown mapping versions before writing records or receipts", async () => {
    const response = await post({
      protocolVersion: 1,
      batch: { ...batch(), mapping_version: "future-mapping-v2" },
    });
    expect(response.status).toBe(422);
    expect(await response.json()).toMatchObject({
      error: { code: "unsupported_mapping" },
    });
    expect(await stored()).toHaveLength(0);
    const receipts = await database.query(
      "SELECT COUNT(*)::int AS count FROM delivery_receipts",
    );
    expect(receipts.rows).toEqual([{ count: 0 }]);
  });
  it("enforces bounded body, record count, identifiers, numeric revisions, shape and cursor", async () => {
    const invalid = [
      batch([]),
      batch(
        Array.from({ length: MAX_DELIVERY_RECORDS + 1 }, (_, index) =>
          record(1, String(index)),
        ),
      ),
      batch([record(), record()]),
      batch([{ ...record(), revision: Number.MAX_SAFE_INTEGER + 1 }]),
      batch([{ ...record(), revision: 0 }]),
      batch([{ ...record(), origin_id: "other" }]),
      batch([{ ...record(), record_id: "x".repeat(513) }]),
      batch([{ ...record(), operation: "delete", payload: {} }]),
    ];
    for (const value of invalid)
      expect((await post({ protocolVersion: 1, batch: value })).status).toBe(
        400,
      );
    expect(
      (
        await post({
          protocolVersion: 1,
          batch: { ...batch(), orgId: "forged" },
        })
      ).status,
    ).toBe(400);
    const big = batch();
    big.records[0].payload!.prompt = "x".repeat(MAX_DELIVERY_BYTES);
    expect((await post({ protocolVersion: 1, batch: big })).status).toBe(413);
    const declaredSmall = await app().request("/v1/delivery/batches", {
      method: "POST",
      headers: { "content-length": "1" },
      body: JSON.stringify({ protocolVersion: 1, batch: big }),
    });
    expect(declaredSmall.status).toBe(413);
    expect(((await declaredSmall.json()) as any).error).toMatchObject({
      code: "delivery_too_large",
      message: `Delivery request exceeds ${MAX_DELIVERY_BYTES} bytes`,
    });
    let nested: unknown = "leaf";
    for (let level = 0; level < 26; level++) nested = { nested };
    const deep = batch();
    deep.records[0].payload!.nested = nested;
    expect((await post({ protocolVersion: 1, batch: deep })).status).toBe(400);

    for (const query of <Record<string, string>[]>[
      { cursor: "x".repeat(4097) },
      { cursor: "not-json" },
      { limit: "101" },
      { include_deleted: "yes" },
    ])
      await expect(listDelivery(db, auth, query)).rejects.toMatchObject({
        status: 400,
      });
    expect(await stored()).toHaveLength(0);
  });
  it("does not trust content-length and rejects malformed JSON and missing scopes", async () => {
    const response = await app().request("/v1/delivery/batches", {
      method: "POST",
      body: "{",
    });
    expect(response.status).toBe(400);
    expect(
      (
        await post(
          { protocolVersion: 1, batch: batch() },
          { ...auth, scopes: ["rth:read"] },
        )
      ).status,
    ).toBe(403);
    const read = await app({ ...auth, scopes: ["rth:sync"] }).request(
      "/v1/delivery/records",
      {},
    );
    expect(read.status).toBe(403);
  });
});

describe("delivery write path does not lose OSS export rows", () => {
  // ai-hist's change feed reports a NULL session as '' (COALESCE), and history
  // tombstones store ''. Rejecting it poisoned the batch: a 400 never advances the
  // cursor, so every later push from that machine failed on the same record.
  it("stores an empty session id as NULL for upserts and tombstones", async () => {
    const upsert = { ...record(1, "no-session"), session_id: "" };
    const tombstone = {
      ...record(2, "no-session-deleted"),
      session_id: "",
      operation: "delete" as const,
      payload: null,
    };
    const response = await post({
      protocolVersion: 1,
      batch: batch([upsert, tombstone]),
    });
    expect(response.status).toBe(200);
    const rows = await stored();
    expect(rows.map((row) => [row.record_id, row.session_id])).toEqual([
      ["no-session", null],
      ["no-session-deleted", null],
    ]);
    const listed = (await listDelivery(db, auth, { include_deleted: "true" }))
      .records;
    expect(listed.map((row) => row.session_id)).toEqual([null, null]);
  });

  it("keeps an empty-session batch exactly replayable and equal to its null spelling", async () => {
    const body = {
      protocolVersion: 1,
      batch: batch([{ ...record(), session_id: "" }]),
    };
    const first = await post(body);
    expect(first.status).toBe(200);
    const receipt = await first.json();
    // Exact replay of the same bytes returns the stored receipt without reapplying.
    expect(await (await post(body)).json()).toEqual(receipt);
    // The digest is over the normalized record, so the same batch spelled with null
    // is the same content: identical receipt, not a batch conflict.
    const nullSpelling = await post({
      protocolVersion: 1,
      batch: batch([{ ...record(), session_id: null }]),
    });
    expect(nullSpelling.status).toBe(200);
    expect(await nullSpelling.json()).toEqual(receipt);
    // And the same revision in another batch is not a revision conflict either.
    const otherBatch = await post({
      protocolVersion: 1,
      batch: batch([{ ...record(), session_id: null }], "batch-2"),
    });
    expect(otherBatch.status).toBe(200);
    const rows = await stored();
    expect(rows).toHaveLength(1);
    expect(rows[0].session_id).toBeNull();
    expect(
      parseDeliveryRequest({
        protocolVersion: 1,
        batch: batch([{ ...record(), session_id: "" }]),
      }).records[0].session_id,
    ).toBeNull();
  });

  it("still rejects a session id that is present but malformed", async () => {
    for (const session_id of ["x".repeat(513), "bad\nid"]) {
      const response = await post({
        protocolVersion: 1,
        batch: batch([{ ...record(), session_id }]),
      });
      expect(response.status).toBe(400);
    }
    expect(await stored()).toHaveLength(0);
  });

  it("keeps SSH and HTTPS git remotes diagnosable while redacting credentials", async () => {
    const payload = {
      source: "claude",
      session_id: "session-fixture",
      prompt: "push to git@github.com:AgentWorkforce/relayhistory.git",
      remote_url: "git@github.com:AgentWorkforce/relayhistory.git",
      https_remote: "https://user:s3cr3tvalue@github.com/o/r",
      token_remote: "https://tok3nvalue@github.com/o/r",
      timestamp_ms: 42,
    };
    const response = await post({
      protocolVersion: 1,
      batch: batch([{ ...record(), payload }]),
    });
    expect(response.status).toBe(200);
    const retained = (await listDelivery(db, auth, {})).records[0]
      .payload as Record<string, unknown>;
    expect(retained.remote_url).toBe(
      "git@github.com:AgentWorkforce/relayhistory.git",
    );
    expect(retained.prompt).toBe(
      "push to git@github.com:AgentWorkforce/relayhistory.git",
    );
    expect(retained.https_remote).toBe(
      "https://user:[REDACTED]@github.com/o/r",
    );
    expect(retained.token_remote).toBe("https://[REDACTED]@github.com/o/r");
  });

  it("marks a session_event payload_truncated when the scrub bound cuts its text", async () => {
    const eventRecord = (
      text: string,
      extra: Record<string, unknown> = {},
    ): HistoryExportRecord => ({
      ...record(),
      kind: "session_event",
      payload: {
        source: "claude",
        session_id: "session-fixture",
        event_uid: "0f1e2d3c-4b5a-6978-8796-a5b4c3d2e1f0:0",
        ts_ms: 42,
        role: "user",
        kind: "text",
        text,
        ...extra,
      },
    });
    const long = "word ".repeat(Math.ceil((MAX_SCRUB_CHARS + 10) / 5));
    expect(servicePayload(eventRecord(long))).toMatchObject({
      payload_truncated: 1,
      text: expect.stringContaining("[relayhistory: truncated"),
    });
    expect(
      servicePayload(eventRecord(long, { payload_truncated: 0 })),
    ).toMatchObject({ payload_truncated: 1 });
    // Truncation inside structured evidence counts too.
    expect(
      servicePayload(
        eventRecord("short", { token_json: JSON.stringify({ note: long }) }),
      ),
    ).toMatchObject({ payload_truncated: 1 });
    // Untruncated rows keep whatever the client sent, and gain nothing.
    expect(servicePayload(eventRecord("short"))).not.toHaveProperty(
      "payload_truncated",
    );
    expect(
      servicePayload(eventRecord("short", { payload_truncated: 0 })),
    ).toMatchObject({ payload_truncated: 0 });
    // Kinds without the local column do not gain one.
    expect(
      servicePayload({
        ...record(),
        payload: { ...record().payload, prompt: long },
      }),
    ).not.toHaveProperty("payload_truncated");

    const response = await post({
      protocolVersion: 1,
      batch: batch([eventRecord(long)]),
    });
    expect(response.status).toBe(200);
    expect((await stored())[0].payload).toMatchObject({ payload_truncated: 1 });
  });

  it("leaves opaque identifier columns byte-for-byte intact", () => {
    const ids = {
      event_uid: "0f1e2d3c-4b5a-6978-8796-a5b4c3d2e1f0:3",
      tool_use_id: "toolu_01AbCdEfGhIjKlMnOpQrStUv",
      message_id: "msg_01XyZabcdefghijklmnop",
      request_id: "req_011CabcdefGHIJKLmnop",
      provider_message_id: "chatcmpl-9aBcDeFgHiJkLmNoP",
      parent_id: "a1b2c3d4-e5f6-7890-abcd-ef0123456789",
      agent_id: "agent-7f3a",
      subagent_session_id: "b2c3d4e5-f6a7-8901-bcde-f01234567890",
      commit_sha: "0123456789abcdef0123456789abcdef01234567",
    };
    expect(
      servicePayload({
        ...record(),
        kind: "session_event",
        payload: { ...ids },
      }),
    ).toEqual(ids);
  });
});

describe("bounded delivery readback", () => {
  it("returns large records on consecutive byte-bounded pages without omissions", async () => {
    for (const id of ["large-a", "large-b"]) {
      const item = record(1, id);
      item.kind = "tool_call";
      item.payload = {
        args_json: JSON.stringify(
          Array.from({ length: 9 }, () => "λ".repeat(100_000)),
        ),
      };
      expect(
        (await post({ protocolVersion: 1, batch: batch([item], id) })).status,
      ).toBe(200);
    }
    const first = await listDelivery(db, auth, { limit: "100" });
    expect(first.records.map((row) => row.record_id)).toEqual(["large-a"]);
    expect(first.nextCursor).toBeTruthy();
    expect(
      new TextEncoder().encode(JSON.stringify(first)).length,
    ).toBeLessThanOrEqual(MAX_DELIVERY_PAGE_BYTES);
    const second = await listDelivery(db, auth, {
      limit: "100",
      cursor: first.nextCursor!,
    });
    expect(second.records.map((row) => row.record_id)).toEqual(["large-b"]);
    expect(second.nextCursor).toBeNull();
    expect(
      new TextEncoder().encode(JSON.stringify(second)).length,
    ).toBeLessThanOrEqual(MAX_DELIVERY_PAGE_BYTES);
  });
  it("rejects scrub expansion that could not fit a readback page before committing", async () => {
    const item = record();
    item.kind = "tool_call";
    item.payload = {
      args_json: JSON.stringify(
        Array.from({ length: 6 }, () => "pwd=x ".repeat(40_000)),
      ),
    };
    const body = { protocolVersion: 1, batch: batch([item]) };
    expect(new TextEncoder().encode(JSON.stringify(body)).length).toBeLessThan(
      MAX_DELIVERY_BYTES,
    );
    expect((await post(body)).status).toBe(413);
    expect(await stored()).toHaveLength(0);
    expect(
      (await database.query("SELECT * FROM delivery_receipts")).rows,
    ).toHaveLength(0);
  });
});
