import assert from "node:assert/strict";
import test from "node:test";
import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  packageName,
  platforms,
  plugins,
  repositoryField,
} from "./history-package-contract.mjs";
import {
  localCoreDependency,
  setReleaseVersion,
} from "./set-release-version.mjs";

const scripts = dirname(fileURLToPath(import.meta.url));
/** Deliberately older than any release, so every field has to be rewritten. */
const stale = "0.1.0";

function fixture(info) {
  const name = packageName(info);
  const optionalDependencies = Object.fromEntries(
    Object.keys(platforms).map((platform) => [`${name}-${platform}`, stale]),
  );
  const devDependencies = { "ai-hist": localCoreDependency };
  const peerDependencies = { "ai-hist": `^${stale}` };
  return {
    manifest: {
      name,
      version: stale,
      license: "MIT",
      // Real manifests must declare this or `npm publish --provenance` fails
      // E422; the contract asserts it, so the fixture carries it too.
      repository: repositoryField("plugins/fixture/sdk"),
      peerDependencies,
      devDependencies,
      optionalDependencies,
    },
    lock: {
      name,
      version: stale,
      lockfileVersion: 3,
      requires: true,
      packages: {
        "": {
          name,
          version: stale,
          devDependencies,
          optionalDependencies: { ...optionalDependencies },
          peerDependencies: { ...peerDependencies },
        },
        "../../../sdk-ts": { name: "ai-hist", version: stale, dev: true },
        "node_modules/ai-hist": { resolved: "../../../sdk-ts", link: true },
        ...Object.fromEntries(
          Object.keys(platforms).map((platform) => [
            `node_modules/${name}-${platform}`,
            { version: stale, optional: true, license: "MIT" },
          ]),
        ),
      },
    },
  };
}

/** The crate each plugin's helper (and, for relayhistory, the probe) builds
 * from. Its own Cargo workspace, so the lock beside it names it too. */
function crateFixture(info) {
  return {
    manifest: `[package]
name = "${info.binary}"
version = "${stale}"
edition = "2021"
license = "MIT"

[workspace]

[dependencies]
anyhow = "1"
`,
    lock: `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "anyhow"
version = "1.0.99"

[[package]]
name = "ai-hist"
version = "${stale}"
dependencies = [
 "anyhow",
]

[[package]]
name = "${info.binary}"
version = "${stale}"
dependencies = [
 "ai-hist",
 "anyhow",
]
`,
  };
}

/** The core crate every plugin depends on by path, and the root lock naming it. */
const coreFixture = {
  manifest: `[package]
name = "ai-hist"
version = "${stale}"
edition = "2021"
license = "MIT"
`,
  lock: `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "ai-hist"
version = "${stale}"

[[package]]
name = "ai-hist-napi"
version = "${stale}"
dependencies = [
 "ai-hist",
]
`,
};

/** A throwaway checkout holding only the files a release version rewrites. */
async function stagePlugins(crlf = false) {
  const root = await mkdtemp(join(tmpdir(), "set-release-version-"));
  const eolCore = (text) => (crlf ? text.replace(/\n/g, "\r\n") : text);
  await mkdir(join(root, "crates", "ai-hist"), { recursive: true });
  await writeFile(
    join(root, "crates", "ai-hist", "Cargo.toml"),
    eolCore(coreFixture.manifest),
  );
  await writeFile(join(root, "Cargo.lock"), eolCore(coreFixture.lock));
  for (const [plugin, info] of Object.entries(plugins)) {
    const directory = join(root, "plugins", plugin, "sdk");
    await mkdir(directory, { recursive: true });
    const { manifest, lock } = fixture(info);
    await writeFile(
      join(directory, "package.json"),
      JSON.stringify(manifest, null, 2) + "\n",
    );
    await writeFile(
      join(directory, "package-lock.json"),
      JSON.stringify(lock, null, 2) + "\n",
    );
    const rust = join(root, "plugins", plugin, "rust");
    await mkdir(rust, { recursive: true });
    const crate = crateFixture(info);
    // Windows checkouts carry CRLF; the stamping must not depend on that.
    const eol = (text) => (crlf ? text.replace(/\n/g, "\r\n") : text);
    await writeFile(join(rust, "Cargo.toml"), eol(crate.manifest));
    await writeFile(join(rust, "Cargo.lock"), eol(crate.lock));
  }
  return root;
}
const read = (root, plugin, file) =>
  readFile(join(root, "plugins", plugin, "sdk", file), "utf8");
const readCrate = (root, plugin, file) =>
  readFile(join(root, "plugins", plugin, "rust", file), "utf8");
const readCore = (root, file) => readFile(join(root, file), "utf8");
const files = (root) =>
  Promise.all([
    readCore(root, "crates/ai-hist/Cargo.toml"),
    readCore(root, "Cargo.lock"),
    ...Object.keys(plugins).flatMap((plugin) => [
      ...["package.json", "package-lock.json"].map((file) =>
        read(root, plugin, file),
      ),
      ...["Cargo.toml", "Cargo.lock"].map((file) =>
        readCrate(root, plugin, file),
      ),
    ]),
  ]);

test("the release version reaches every manifest, peer range and lock coordinate", async () => {
  const root = await stagePlugins();
  const version = "9.9.9";
  const result = spawnSync(
    process.execPath,
    [join(scripts, "set-release-version.mjs"), version, root],
    { encoding: "utf8" },
  );
  assert.equal(result.status, 0, result.stderr);
  // The core crate is a path dependency of every plugin crate, and Cargo
  // compares its manifest version with the plugin lock's entry under
  // --locked; the helper matrix stamps on its own checkout, so this script
  // must move the manifest and the root lock with it. Nothing else moves.
  const coreManifest = await readCore(root, "crates/ai-hist/Cargo.toml");
  const rootLock = await readCore(root, "Cargo.lock");
  assert.ok(
    coreManifest.includes(`[package]\nname = "ai-hist"\nversion = "${version}"\n`),
    coreManifest,
  );
  assert.ok(
    rootLock.includes(`[[package]]\nname = "ai-hist"\nversion = "${version}"\n`),
    rootLock,
  );
  assert.ok(
    rootLock.includes(`[[package]]\nname = "ai-hist-napi"\nversion = "${stale}"\n`),
    rootLock,
  );
  for (const [plugin, info] of Object.entries(plugins)) {
    const manifest = JSON.parse(await read(root, plugin, "package.json"));
    const lock = JSON.parse(await read(root, plugin, "package-lock.json"));
    // The helper and the probe report CARGO_PKG_VERSION, so the crate and the
    // lock beside it carry the release version too — and nothing else does.
    const crate = await readCrate(root, plugin, "Cargo.toml");
    const crateLock = await readCrate(root, plugin, "Cargo.lock");
    assert.ok(
      crate.includes(
        `[package]\nname = "${info.binary}"\nversion = "${version}"\n`,
      ),
      crate,
    );
    assert.ok(
      crateLock.includes(
        `[[package]]\nname = "${info.binary}"\nversion = "${version}"\n`,
      ),
      crateLock,
    );
    // The core crate is a path dependency whose version the same release
    // bumps; a stale entry fails every `--locked` build in CI (0.18.8).
    assert.ok(
      crateLock.includes(
        `[[package]]\nname = "ai-hist"\nversion = "${version}"\n`,
      ),
      crateLock,
    );
    assert.ok(
      crateLock.includes('name = "anyhow"\nversion = "1.0.99"\n'),
      crateLock,
    );
    assert.equal(manifest.version, version);
    assert.equal(manifest.peerDependencies["ai-hist"], `^${version}`);
    // Plugins keep building against the checkout SDK.
    assert.equal(manifest.devDependencies["ai-hist"], localCoreDependency);
    assert.equal(lock.version, version);
    assert.equal(lock.packages[""].version, version);
    assert.equal(lock.packages[""].peerDependencies["ai-hist"], `^${version}`);
    assert.equal(lock.packages["../../../sdk-ts"].version, version);
    for (const platform of Object.keys(platforms)) {
      const name = packageName(info, platform);
      const [os, cpu, libc] = platforms[platform];
      assert.equal(manifest.optionalDependencies[name], version);
      assert.equal(lock.packages[""].optionalDependencies[name], version);
      assert.deepEqual(lock.packages[`node_modules/${name}`], {
        version,
        resolved: `https://registry.npmjs.org/${name}/-/${info.name}-${platform}-${version}.tgz`,
        optional: true,
        os: [os],
        cpu: [cpu],
        ...(libc ? { libc: [libc] } : {}),
        license: "MIT",
      });
    }
  }
});

test("re-applying the same version rewrites nothing", async () => {
  const root = await stagePlugins();
  await setReleaseVersion("1.2.3", root);
  const first = await files(root);
  await setReleaseVersion("1.2.3", root);
  assert.deepEqual(await files(root), first);
});

test("only a stable release version is accepted", async () => {
  const root = await stagePlugins();
  const before = await files(root);
  for (const version of ["", "latest", "1.2", "1.2.3-rc.1", "v1.2.3"]) {
    await assert.rejects(() => setReleaseVersion(version, root));
  }
  assert.deepEqual(await files(root), before);
});

test("crate stamping survives CRLF checkouts", async () => {
  const root = await stagePlugins(true);
  await setReleaseVersion("1.2.3", root);
  assert.match(
    await readCore(root, "crates/ai-hist/Cargo.toml"),
    /\[package\]\r\nname = "ai-hist"\r\nversion = "1\.2\.3"/,
  );
  for (const plugin of Object.keys(plugins)) {
    const manifest = await readCrate(root, plugin, "Cargo.toml");
    const lock = await readCrate(root, plugin, "Cargo.lock");
    assert.match(manifest, /\[package\]\r\nname = "[^"]+"\r\nversion = "1\.2\.3"/);
    assert.match(lock, /\[\[package\]\]\r\nname = "[^"]+"\r\nversion = "1\.2\.3"/);
    assert.doesNotMatch(manifest, /[^\r]\n/, "line endings must be preserved");
  }
});
